### ISSUE TITLE
AC87u 配置完后出现部分网站无法访问情况

### ISSUE THREAD

**Issue by cs-sun** [zw963/asuswrt-merlin-transparent-proxy#1]
按照说明方法配置完后，访问google.com,facebook.com等网站时，出现无法建立安全连接的情况
<img width="540" alt="2016-10-17 20 53 36" src="https://cloud.githubusercontent.com/assets/15100503/19438303/cded6eee-94ab-11e6-9c58-bee016b3e57b.png">
<img width="486" alt="2016-10-17 20 54 07" src="https://cloud.githubusercontent.com/assets/15100503/19438324/e1448478-94ab-11e6-956e-31c878e04d05.png">
证书显示为dns服务提供商的证书。
但是访问google.co.jp,google.com.hk等可以正常。同时google的手机客户端也可以正常搜索。

**Comment by zw963** [comment]
抱歉刚看到.

我也不知道为什么, 很久以前, 用 GoAgent 也曾经碰到过, 换了我自己的 VPS
就再也没有出现过, 我觉得应该是你的远程服务器不支持 https 协议造成的?

你是用 SS 连接的自己的 VPS 吗?

**Comment by cs-sun** [comment]
是的，连接的是自己的vps。更换至另一个地区的vps后问题消失，但是原因未知。
