### ISSUE TITLE
部署成功但没有效果

### ISSUE THREAD

**Issue by ohmyarch** [zw963/asuswrt-merlin-transparent-proxy#10]
所有网页（包括国内的）都打不开

```zsh
$ ./ss+dnsmasq asus@192.168.1.1
```
asus@192.168.1.1's password: 
patch_dnsmasq                                                                                    100%  451   448.5KB/s   00:00    
S22ss-tunnel                                                                                     100%  261   289.1KB/s   00:00    
accelerated-domains.china.conf                                                                   100%    0     0.0KB/s   00:00    
foreign_domains.conf                                                                             100%   34    40.1KB/s   00:00    
accelerated-domains-ipset.china.conf                                                             100%    0     0.0KB/s   00:00    
shadowsocks.json                                                                                 100%  187    17.5KB/s   00:00    
restart_dnsmasq                                                                                  100%   83   100.9KB/s   00:00    
iptables.sh                                                                                      100% 1916     1.5MB/s   00:00    
asus@192.168.1.1's password: 
Installing bash (4.3.42-1a) to root...
Downloading http://pkg.entware.net/binaries/armv7/bash_4.3.42-1a_armv7soft.ipk
Configuring bash.
asus@192.168.1.1's password: 
***********************************************************
Remote deploy scripts is started !!
***********************************************************
Package shadowsocks-libev (2.6.1-1) installed in root is up to date.
Deploy success! Rebooting, please wait ...
If any error occur, Please unplug U disk and reboot again!

```zsh
asus@RT-AC68U-EA68:/tmp/home/root# /opt/etc/init.d/S22shadowsocks check
```
 Checking ss-redir...              alive.

```zsh
asus@RT-AC68U-EA68:/tmp/home/root# /opt/etc/init.d/S22ss-tunnel check
```
 Checking ss-tunnel...              alive.

**Comment by zw963** [comment]
看到你用的是 asus@192.168.1.1, asus 是超级用户吗? 我都是用 admin@192.168.1.1

我的脚本其实缺乏一些如果中途执行失败的处理, 虽然最后重启了, 可能并没有成功.

你可以把 U 盘重新格式化一下, 使用 admin 再试一次.

**Comment by ohmyarch** [comment]
不是超级用户 随便起的名字 u盘也是部署前才格式化的。现在不知道如何排错

**Comment by ohmyarch** [comment]
又重新格式化了u盘 还原了/jffs 再部署 还是这样 国内的都上不去了
路由器型号是ASUS RT-AC68U
固件版本是380.65_2

**Comment by zw963** [comment]
@ohmyarch , 你重新尝试, 是使用的 admin 用户吗? 你用 admin 再试一下.

**Comment by zw963** [comment]
我只是在公司的 AC87U 和我自己的 AC66U 测试过, 麻烦在你路由器上运行 
```sh
ipset -v
```
告诉我下返回的信息.

**Comment by zw963** [comment]
你的问题应该是 /opt/etc/iptables.sh 这个没有执行成功, 确保这个文件 是可执行的(ls 是绿色的), 你可以手动运行一次, 例如:

```sh
# /opt/etc/iptables.sh
```

 看看返回什么.

**Comment by ohmyarch** [comment]
😂找到原因了 路由器重启之后还要在电脑这边断开连接重新连 效果很好 翻遍了网上就找到这一个符合要求的项目 感谢
