### ISSUE TITLE
或许该尝试下chinadns-ng而不是dnscrypt？

### ISSUE THREAD

**Issue by LaplaceTor** [zw963/asuswrt-merlin-transparent-proxy#100]
[https://github.com/zfl9/chinadns-ng](url)
ChinaDNS-NG为ChinaDNS 的个人重构版本，特点：

使用 epoll 和 ipset(netlink) 实现，性能更强。
完整支持 IPv4 和 IPv6 协议，兼容 EDNS 请求和响应。
手动指定国内 DNS 和可信 DNS，而非自动识别，更加可控。
修复原版对保留地址的处理问题，去除过时特性，只留核心功能。
修复原版对可信 DNS 先于国内 DNS 返回而导致判断失效的问题。
支持 gfwlist/chnlist 黑/白名单匹配模式，效率比 dnsmasq 更高。

如果你指定的 china-dns 上游为个人、组织内部的 DNS 服务器，且该 DNS 服务器会返回某些特殊的解析记录（即：包含保留地址的解析记录，比如使用内网 DNS 服务器作为国内上游 DNS），且你希望 chinadns-ng 会接受这些特殊的 DNS 响应（即将它们判定为国内 IP），那么你需要将对应的保留地址段加入到 chnroute、chnroute6 ipset 中。注意：chinadns-ng 判断是否为"国内 IP"的核心就是查询 chnroute、chnroute6 这两个 ipset 集合，程序内部没有任何隐含的判断规则。

chinadns的老毛病貌似修了，翻了下感觉可行，但目前比较犹豫是直接把路由器当作上游DNS还是chinadns作为上游，主要还有个division用了dnsmasq，感觉分别会有冗余查询或者重定向错误

**Comment by zw963** [comment]
谢谢，最近有空一定去了解下，以前的 ChinaDNS 感觉从来没有工作过，所以引入的 DNS crypt，不过，我自己用的是我的另一个项目，https://github.com/zw963/asuswrt-merlin-v2ray，解决了我遇到的所有问题， V2Ray 直接就 serve as DNS server，效果还不错。

**Comment by gitx6** [comment]
关于 ChinaDNS-NG 讨论：
https://github.com/coolsnowwolf/lede/issues/3966#issuecomment-602988997

**Comment by zw963** [comment]
其实我很想知道, 你们还在用 dnscrypt 或 chinadns-NG, 而没有切换到 V2Ray,  具体是什么原因吗? 感觉路由器跑不动吗?

**Comment by LaplaceTor** [comment]
> 其实我很想知道, 你们还在用 dnscrypt 或 chinadns-NG, 而没有切换到 V2Ray, 具体是什么原因吗? 感觉路由器跑不动吗?

确实是跑不动，把ADBLOCK放路由器使得负担较高，再加上V2RAYDNS的话时不时会出现连接丢失的情况（查询所耗时间过多），CHINADNS或者SMARTDNS之类的能减轻负担，不过国内外都有CDN的网站容易重定向次数过多

考虑过把ADBLOCK放vps，但比较想通过ADBLOCK把国内的广告也去掉而不是只过滤国外链接，因此作罢

**Comment by zw963** [comment]
你是什么路由器? 据我所知, 有的用户使用 AC87U 大概这个配置的路由器也可以跑, 前提是, 你要开启 swap 文件.

> 但比较想通过ADBLOCK把国内的广告也去掉而不是只过滤国外链接，因此作罢

你的这个 ADBLOCK 和 V2Ray 内置的广告过滤有区别吗?

**Comment by LaplaceTor** [comment]
> 你是什么路由器? 据我所知, 有的用户使用 AC87U 大概这个配置的路由器也可以跑, 前提是, 你要开启 swap 文件.

我用的AC68U(就是87U官网被对比的那台)，单U双核
事实上是，广告过滤和SWAP文件开启之后，GUI页面已经变卡，魔法上网确实可以开，但试过单独弄gfwlist用来分流，变得更卡因而寻求更低消耗的插件，诸如chinadns和smartdns，不过后者确实问题还比较多

> > 但比较想通过ADBLOCK把国内的广告也去掉而不是只过滤国外链接，因此作罢
> 你的这个 ADBLOCK 和 V2Ray 内置的广告过滤有区别吗?

事实上就是entware的广告过滤 https://diversion.ch/diversion/diversion.html ，v2ray内置在稍作考虑后并未使用，毕竟自己买的VPS只有单核500M内存

**Comment by zw963** [comment]
> 事实上就是entware的广告过滤 https://diversion.ch/diversion/diversion.html ，v2ray内置在稍作考虑后并未使用，毕竟自己买的VPS只有单核500M内存

我曾经有想过集成 diversion 进来这个脚本, 不过, 既然后来有 V2Ray, 我就没在做了. 我感觉你没办法直接使用 diversion 和当前部署脚本吧?

你的 VPS 内存是小了点, 你买的哪里的? 现在还有这么低的配置?

**Comment by LaplaceTor** [comment]
> 我曾经有想过集成 diversion 进来这个脚本, 不过, 既然后来有 V2Ray, 我就没在做了. 我感觉你没办法直接使用 diversion 和当前部署脚本吧?

对，我没有细看你的脚本但我认为很可能会有冲突因此没有直接使用
 
> 你的 VPS 内存是小了点, 你买的哪里的? 现在还有这么低的配置?

阿里云国际，我也嫌内存小不过有300MBPS带宽和1T流量，5刀的价格很实惠了，速度也快，唯一问题是得有国外信用卡，另外我找的机场主他也不是主用阿里云的，因而我分到一个能看奈飞的IP

国内部分地区GITHUB被中转，如果被告知证书不安全裸连流量有可能被监听，如有此情况建议谨慎言行
