### ISSUE TITLE
`Failed to connect to raw.githubusercontent.com port 443: Connection refused`

### ISSUE THREAD

**Issue by chinaq** [zw963/asuswrt-merlin-transparent-proxy#101]
`Failed to connect to raw.githubusercontent.com port 443: Connection refused` 出现这个问题，连不上，有什么办法可以解决吗？谢谢

**Comment by zw963** [comment]
你访问 GitHub 被墙了，不过多试几次一般还是可以过去的

**Comment by BoxingP** [comment]
add below to router's /etc/hosts, then should work 
`151.101.208.133 raw.githubusercontent.com`

**Comment by zw963** [comment]
> add below to router's /etc/hosts, then should work
> `151.101.208.133 raw.githubusercontent.com`

Cool, thank you.
