### ISSUE TITLE
执行部署出错

### ISSUE THREAD

**Issue by c1rew** [zw963/asuswrt-merlin-transparent-proxy#11]
路由器：AC66U
电脑：Mac mini
终端：iTerm zsh

在路由器内部 opkg可以使用，用脚本部署出错

[~/work/asus-merlin]$ ./ss+dnsmasq vinoadmin@192.168.2.1                                 
sed: -i may not be used with stdin
./ss+dnsmasq: line 32: opkg: command not found
./ss+dnsmasq: line 35: ipset: command not found
./ss+dnsmasq: line 43: opkg: command not found

ss+dnsmasq 脚本前面加上 set -x，日志如下：
[~/work/asus-merlin]$ ./ss+dnsmasq vinoadmin@192.168.2.1                                 *[master]
+ source ./functions/deploy_start.sh
++ export -f deploy_start
++ alias export=__export
+ export target=vinoadmin@192.168.2.1
+ target=vinoadmin@192.168.2.1
+ '[' '!' -e ./route/opt/etc/shadowsocks.json ']'
+ ./generate_dns
sed: -i may not be used with stdin
+ which ipset
+ opkg install ipset4
./ss+dnsmasq: line 32: opkg: command not found
++ ipset -v
++ grep -o 'version.*[0-9]'
./ss+dnsmasq: line 35: ipset: command not found
++ head -n1
++ cut '-d ' -f2
+ ipset_protocal_version=
+ set -e
+ '[' '' == 6 ']'
+ opkg install shadowsocks-libev iptables
./ss+dnsmasq: line 43: opkg: command not found

**Comment by zw963** [comment]
手头没有 mac,  你进入项目目录, 执行:

```sh
sh -x ./generate_dns
```

贴一下输出提示.

**Comment by c1rew** [comment]
[~/work/asus-merlin]$ sh -x ./generate_dns                                               
+ target=route/opt/etc/dnsmasq.d/
+ mkdir -p route/opt/etc/dnsmasq.d/
+ which wget
+ wget -q -O route/opt/etc/dnsmasq.d//accelerated-domains.china.conf https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf

+ sed 's#server=\(.*\)114.114.114.114#ipset=\1FREEWEB#' route/opt/etc/dnsmasq.d//accelerated-domains.china.conf
+ sed -i 's|^\(server.*\)/[^/]*$|\1/#|' route/opt/etc/dnsmasq.d//accelerated-domains.china.conf
sed: -i may not be used with stdin

**Comment by zw963** [comment]
尝试修复 ea30edd, 麻烦拉下最新的代码, 再试一下.

**Comment by c1rew** [comment]
可以了，也可以部署了，但是在路由器上，ss还是没有运行起来，有空再看看怎么回事，脚本里面有些地方比较模糊，我还没全看懂哈

**Comment by zw963** [comment]
> ss还是没有运行起来

你怎么知道没有运行起来? 实际运行的是 ss-redir, 而不是 ss-local, 你可以看下 #9
