### ISSUE TITLE
如果服务器是SSR服务器，这个脚本可以用吗？

### ISSUE THREAD

**Issue by noahge** [zw963/asuswrt-merlin-transparent-proxy#12]
服务器是SSR服务器的话，有两个混淆选项，请问这个怎么加上去呢？

**Comment by zw963** [comment]
@jackge0323 , 不懂啊, 不明白什么是 SSR.

这个只是客户端配置, 使用这个脚本之前, 确保你自己可以手动的使用 ss ``全局/浏览器`` 上网.

**Comment by noahge** [comment]
SSR就是SS的一个新的分支（不知道这么解释对不对，哈哈），链接是：https://github.com/breakwa11/shadowsocks-rss，可以看一下，和普通SS的区别似乎就是可以添加协议混淆，我看你的脚本配置里没有添加混淆设置的地方，用这个脚本的话，能不能用这个服务器端呢？帮忙看下，谢谢了。

**Comment by zw963** [comment]
是否可以, 那取决于 opkg 包管理提供的  ss 客户端是否可以连接到你的服务器, 你需要自己手动试一下.
如果不可以, 那么你可能需要下载客户端源码自己编译了.
