### ISSUE TITLE
AC68U SS+dnsmasq 部署出错

### ISSUE THREAD

**Issue by gitx6** [zw963/asuswrt-merlin-transparent-proxy#16]
路由器部署过程中出错信息如下：
Package bash (4.3.42-1a) installed in root is up to date.
 ***********************************************************
 Remote deploy scripts is started !!
 ***********************************************************
 Package shadowsocks-libev (2.6.1-1) installed in root is up to date.
 /opt/bin/bash: line 395: add_service: command not found
 /opt/bin/bash: line 402: add_service: command not found
 /opt/bin/bash: line 120: sudo: unbound variable

技术小白求指导。谢谢!

**Comment by gitx6** [comment]
路由器Firmware:380.65_4
主机使用虚拟机Centos

**Comment by gitx6** [comment]
set -x 所有的输出课参见gist
https://gist.github.com/wangxin6/37743a5f17212bdc32f0bc1e423422ef

**Comment by zw963** [comment]
@wangxin6 , 你好, 之前重构引入了一个 bug,  没有测试真心不行呀, 看来 bash shell  测试也得o搞起来, 麻烦你再试一下. 谢谢.

**Comment by gitx6** [comment]
相同的出错信息。

发现两个问题：

1. 路由器上/jffs/scripts/里面只有三个scripts （post-mount、  services-start 、 services-stop）没有add_service，replace_regex等

2. Web UI 里面Administration -> System->  Enable JFFS custom scripts and configs已经设置为Yes。但是script无法运行。提示如下：
admin@RT-AC68U-DA00:/jffs/scripts# services-start 
-sh: services-start: not found

**Comment by gitx6** [comment]
需要加环境变量
export PATH=‘/jffs/scripts’

**Comment by tranter1991** [comment]
Installing shadowsocks-libev (3.0.6-1) to root...
....
Collected errors:
 * resolve_conffiles: Existing conffile /opt/etc/shadowsocks.json is different from the conffile in the new package. The new conffile will be placed at /opt/etc/shadowsocks.json-opkg.
Configuring libev.
Configuring libmbedtls.
Configuring libsodium.
Configuring libudns.
Configuring libpcre.
Configuring zlib.
Configuring shadowsocks-libev.
Deploy success! Rebooting, please wait ...
If any error occur, Please unplug U disk and reboot again!
/opt/bin/bash: line 118: syntax error near unexpected token `fi'
/opt/bin/bash: line 118: `fi'

我使用ubuntu 17.04虚拟机运行 ./ss+dnsmasq admin@192.168.1.1
出现上面的错误，add_service: command not found错误没有了
这时候路由重启后网络能连接但是dns无法解析，不知道从何入手:<，只能恢复出厂了

**Comment by gitx6** [comment]
我重新格式化U盘，重新安装也显示部署成功了。也是有同样的信息：
/opt/bin/bash: line 118: syntax error near unexpected token fi' /opt/bin/bash: line 118:fi'

重启路由器后，国内国外网站都不可以访问。一直在解析DNS。

拔掉U盘后，关闭、打开电源后可以上网，不用恢复出厂。

**Comment by zw963** [comment]
> resolve_conffiles: Existing conffile /opt/etc/shadowsocks.json is different from the conffile in the new package. The new conffile will be placed at /opt/etc/shadowsocks.json-opkg.
> Configuring libev.
> Configuring libmbedtls.
> Configuring libsodium.
> Configuring libudns.
> Configuring libpcre.
> Configuring zlib.
> Configuring shadowsocks-libev.
> Deploy success! Rebooting, please wait ...
> If any error occur, Please unplug U disk and reboot again!
> /opt/bin/bash: line 118: syntax error near unexpected token fi' /opt/bin/bash: line 118:fi'

当出现 fi 错误这个提示, 其实代表你已经部署成功了.

你检查下你的 `/opt/etc/shadowsocks.json` , 可能是这个文件配置有问题.

**Comment by zw963** [comment]
> 路由器上/jffs/scripts/里面只有三个scripts （post-mount、 services-start 、 services-stop）没有add_service，replace_regex等

这些是我定义的部署时才存在的函数, 不是命令.

**Comment by zw963** [comment]
这个问题应该已解决, 有问题, 提反馈, 我再 open.
