### ISSUE TITLE
Mac OS 部署路由器脚本开始后退出

### ISSUE THREAD

**Issue by gitx6** [zw963/asuswrt-merlin-transparent-proxy#17]
Mac OS部署路由器脚本开始后退出。终端显示如下：

accelerated-domains-ipset.china.conf          100%  981KB 980.6KB/s   00:00    
foreign_domains.conf                          100%   34     0.0KB/s   00:00    
S22ss-tunnel                                  100%  261     0.3KB/s   00:00    
iptables.sh                                   100% 1916     1.9KB/s   00:00    
patch_dnsmasq                                 100%  451     0.4KB/s   00:00    
restart_dnsmasq                               100%   83     0.1KB/s   00:00    
shadowsocks.json                              100%  510     0.5KB/s   00:00    
admin@192.168.1.1's password: 
Package bash (4.3.42-1a) installed in root is up to date.
admin@192.168.1.1's password: 
***********************************************************
Remote deploy scripts is started !!
***********************************************************
$

**Comment by gitx6** [comment]
+ ssh admin@192.168.1.1 /opt/bin/bash
***********************************************************
Remote deploy scripts is started !!
***********************************************************
+ exit 0

**Comment by tranter1991** [comment]
我也遇到同样的问题, 也是mac os
RT-AC68U_380.66_4  macos 10.11.6

**Comment by zw963** [comment]
@wangxin6 , 你好, 之前重构引入了一个 bug, 你再试一下.

**Comment by zw963** [comment]
@tranter1991 , mac 可能还有其他问题, 我今天使用 mac 实际运行一次, 试试看.

**Comment by gitx6** [comment]
这个issue应该和issue 13一样。

hexid26 commented on Apr 23
不好意思，犯二了。。。当时是演示用的，所以换了个 mac。真实部署的机器都是 MAC，都有 wget。。。都是代码狗。。。brew 必装的。。。wget 也是如此。。。。
输出都是到这一步：

***********************************************************
Remote deploy scripts is started !!
***********************************************************
然后就回到了命令行。。。我也觉得很奇怪。。。感觉你在deploy start.sh中的函数定义脚本都没有执行。。。

**Comment by zw963** [comment]
@wangxin6 , 这个我今天试过了, 出问题的步骤不是 wget, 我现在换成 curl 了, 不需要 wget 了.

真正出问题的地方是,  我生成的部署字符串无法通过 ssh 命令传入, ssh 只是执行了一个空命令, 然后推出了.

我明天再想想该如何解决.

Linux 应该没有问题了.

**Comment by gitx6** [comment]
Fix to use brew version bash if installed in OSX 是否也要部署在ss+dnsmasq+chinadns脚本上？

**Comment by zw963** [comment]
OSX 下面上次测试, 仍旧不可用, 待解决

**Comment by qianlongzju** [comment]
我也遇到同样的问题，

**Comment by zw963** [comment]
@qianlongzju ,  我不用 Mac, 谁可以给点为什么 Mac 下面没有继续执行的建议?

**Comment by qianlongzju** [comment]
@zw963 我试了下里面的命令，貌似没有add_service

**Comment by zw963** [comment]
OSX 下无法部署的 issue 已经解决,  正好, shadowsocks-libev 大版本升级了, 有空大家帮忙在 Mac 下测试下.
