### ISSUE TITLE
ac68u部署后ss-redir没有启动

### ISSUE THREAD

**Issue by gitx6** [zw963/asuswrt-merlin-transparent-proxy#18]
按照脚本自动部署完成后，ss-redir没有启动。

**Comment by gitx6** [comment]
admin@RT-AC68U-DA00:/tmp/mnt/sda1/entware/etc# ps |grep ss-redir
 1619 admin     1396 S    grep ss-redir

**Comment by gitx6** [comment]
admin@RT-AC68U-DA00:/tmp/mnt/sda1/entware/etc# ls shadowsocks.json
shadowsocks.json

shadowsocks.json已经存在

**Comment by zw963** [comment]
你重新读下 [README](https://github.com/zw963/asuswrt-merlin-transparent-proxy#初始化-jffs)

参照这句话: 提示: 如果因为各种原因, 之后有任何步骤执行失败, 可以重复执行本步骤, 再次部署, 注意每次初始化后, 需要手动点击重启路由器.

**Comment by gitx6** [comment]
注意每次初始化后, 需要手动点击重启路由器._

已重复部署多次。部署完以后，路由器自动重启；完成以后webUI手工点击重启路由器多次。关闭/打开电源多次。仍然同样问题。 ss-redir后面没有shadowsocks.json参数。

**Comment by gitx6** [comment]
我找到问题。

把shadowsocks.json例子里面的‘//'当成注释一起复制进文件了。这些行里面的所有//需要删除。

**Comment by wangxin6** [comment]
我找到问题。

把shadowsocks.json例子里面的‘//'当成注释一起复制进文件了。这些行里面的所有//需要删除。
