### ISSUE TITLE
ss+dnsmasq+chinadns部署出错

### ISSUE THREAD

**Issue by gitx6** [zw963/asuswrt-merlin-transparent-proxy#19]
/opt/etc/init.d/目录下没有S56chinadns文件

***********************************************************
Remote deploy scripts is started !!
***********************************************************
Package shadowsocks-libev (3.0.6-1) installed in root is up to date.
sed: /opt/etc/init.d/S56chinadns: No such file or directory

    # 用来转发 DNS 请求到 ss-server.
    replace_string 5353 '5356 -s 114.114.114.114,127.0.0.1:1082,8.8.4.4' /opt/etc/init.d/S56chinadns

**Comment by zw963** [comment]
已经在 dd4b84c 修复, 麻烦测试一下, 如果 OK, 关闭 issue

**Comment by gitx6** [comment]
已成功部署
