### ISSUE TITLE
咨询一下，U盘是不是要一直插入到路由器上才能保证系统运行正常

### ISSUE THREAD

**Issue by superbboy** [zw963/asuswrt-merlin-transparent-proxy#2]
看脚本，是依赖U盘挂接的/opt/目录的

**Comment by zw963** [comment]
是的.

**Comment by gitx6** [comment]
小白请教，是不是可以完全独立安装在路由器内，而不依靠U盘。谢谢。

**Comment by zw963** [comment]
应该可以的.  但是因为使用 opkg 包管理默认的初始化脚本, 它是需要有一个额外磁盘的.
建议保持默认, U 盘如果不考虑离线下载, 随便 2 GB 的就可以了.

**Comment by gitx6** [comment]
有没有考虑过把翻墙和离线下载集成到固件中，然后发布出来？

**Comment by zw963** [comment]
没有时间和精力啊.

再说了, 真集成了, 很多人其实不敢用的, 谁知道里面还安装了什么东西呢?

还是自己配置起来更放心.
