### ISSUE TITLE
BT下载跑ss通道

### ISSUE THREAD

**Issue by gitx6** [zw963/asuswrt-merlin-transparent-proxy#20]
路由器FQ后，BT下载也会走SS通道。会带来SS流量增大。如果是钓鱼的种子，还会被服务商关账号。

如何对指定局域网电脑禁止SS？

**Comment by zw963** [comment]
只要通过域名, 而且域名在国内白名单内, 都不会走 ss 通道,  但是要通过 ip, 这个控制不了.

如果想省流量, 你用那个 chinadns 的版本试试, 会检测 IP.

**Comment by gitx6** [comment]
跑流量问题不大。主要是钓鱼种子，vps服务商收到律师信会关闭端口

**Comment by gitx6** [comment]
ss-rules是不是可以指定局域网某台电脑bypass FQ服务器？

**Comment by zw963** [comment]
没用过, 不知道啊

**Comment by gitx6** [comment]
假定BT下载的电脑ip地址为192.168.1.10。在iptables.sh添加如下记录：

iptables -t nat -A SHADOWSOCKS -s 192.168.1.10 -p tcp -j REDIRECT --to-ports 1080

应该是1080还是1082，还是5356？有些迷糊。

**Comment by gitx6** [comment]
iptables -t nat -I SHADOWSOCKS -s 192.168.1.10  -j RETURN

**Comment by zw963** [comment]
@wangxin6 , 我的  iptables.sh 里面, 有下面这行代码.

```sh
$iptables -t nat -A SHADOWSOCKS -d 192.168.0.0/16 -j RETURN
```

是不是和你提供的类似效果? (-A 和  -l 的差别)

**Comment by gitx6** [comment]
看起来是 -s的参数，指定来源192.168.1.10的流量全部绕过SS

**Comment by zw963** [comment]
> 看起来是 -s的参数，指定来源192.168.1.10的流量全部绕过SS

如果用 -s, 192.168.1.10  这个主机怎么翻?

**Comment by gitx6** [comment]
目的就是不让这个主机翻。避免BT钓鱼种子走SS服务器，被服务商关端口。

**Comment by zw963** [comment]
> 目的就是不让这个主机翻。避免BT钓鱼种子走SS服务器，被服务商关端口。

那么, 这应该属于个人自定义配置了吧, 无论如何, 解决了你的问题就好.

貌似这个 issue, 没有什么可以修改的了, 那就关闭吧.

**Comment by zw963** [comment]
@wangxin6 , 我新增了一个服务器部署脚本,  https://github.com/zw963/asuswrt-merlin-transparent-proxy/blob/master/ss-server_install, 在服务器上一键部署 ss server, 其实你可以考虑下, 自己买个香港的 VPS (很多都一个月试用,不要钱的), 我的一个月才 $9, 200GB, 不限速, 速度超级快, 几乎从不掉线.

自己部署, 应该也没有你这里的问题.

**Comment by gitx6** [comment]
这个属于技术探讨。谢谢。
