### ISSUE TITLE
咨询：增加bogus-nxdomain.china.conf

### ISSUE THREAD

**Issue by gitx6** [zw963/asuswrt-merlin-transparent-proxy#21]
如果增加bogus-nxdomain.china.conf是不是直接把这个文件scp复制到路由器/opt/etc/dnsmasq.d/，然后输入：
admin@RT-AC66U-20F0: ./patch_dnsmasq

**Comment by zw963** [comment]
``patch_dnsmasq`` 每次路由重启时会自动执行一次, 不重启无需重新执行,  修改了 dnsmasq 配置, 要执行的是 restart_dnsmasq.

>> 如果增加bogus-nxdomain.china.conf是不是直接把这个文件scp复制到路由器/opt/etc/dnsmasq.d/

是的.

**Comment by gitx6** [comment]
bogus-nxdomain.china.conf不能在魔都电信使用。会造成国内站点无法访问。
