### ISSUE TITLE
/route/opt/etc/iptables.sh 脚本错误

### ISSUE THREAD

**Issue by gitx6** [zw963/asuswrt-merlin-transparent-proxy#23]
/route/opt/etc/iptables.sh脚本第37行
 $iptables -t nat -A SHADOWSOCKS --dport 22334 -j RETURN
应该为
 $iptables -t nat -A SHADOWSOCKS -p tcp --dport 22334 -j RETURN

参照：
https://gist.github.com/wen-long/8644243

**Comment by zw963** [comment]
谢谢，明天检查并统一修复下

2017年6月30日 18:47，"wangxin6" <notifications@github.com>写道：

**Comment by zw963** [comment]
@wangxin6 ,  请参照 issue #22, 我的回复. 也许, 我们应该全部移除 ``-p  tcp`` 这样的协议限制.

**Comment by gitx6** [comment]
这行脚本对多地址同一端口的有效。对于只有一个地址的可以忽略。
