### ISSUE TITLE
国内阿里云托管的网站无法访问

### ISSUE THREAD

**Issue by gitx6** [zw963/asuswrt-merlin-transparent-proxy#25]
两种方案都尝试过。发现国内阿里云托管的网站无法访问。
比如：
http://www.siwei100.com/
https://www.huanshoulv.com/
http://www.pnlyy.com/

不知道是不是个体现象。谢谢。

**Comment by gitx6** [comment]
一个临时解决方案是把这些域名加到FREEWEB里面。

**Comment by zw963** [comment]
你的  ss 服务端的问题, 我墙内/墙外都可以, 貌似你的墙外不可以.

  你可以自己用 ss 手机客户端试试

**Comment by gitx6** [comment]
twitter，facebook，youtube都可以访问。用ss手机客户端也没有问题。

等有时间，我换个服务商试一下。

**Comment by zw963** [comment]
不是脚本问题.
