### ISSUE TITLE
在虚拟机Ubuntu里面部署到admin@192.168.1.1时出错。。

### ISSUE THREAD

**Issue by Blueplanet20120** [zw963/asuswrt-merlin-transparent-proxy#27]
在虚拟机Ubuntu里面部署到admin@192.168.1.1时提示输入密码，于是输入路由器管理员密码，然后提示拒绝访问，多次都是如此，不知道什么地方的问题。。。
admin@192.168.1.1's password:
Permission denied, please try again.
admin@192.168.1.1's password:
Permission denied, please try again.
admin@192.168.1.1's password:
Permission denied (publickey,password).

**Comment by zw963** [comment]
如果你密码没有输入错误, 那就是你没按照教程开启 ssh 登录.

建议参照这个 http://www.jianshu.com/p/31cbbbc5f9fa/ 设定一下自动登录.
文档中的 github 扮演的角色, 就是你的路由器.
