### ISSUE TITLE
line 512: export: `=': not a valid identifier

### ISSUE THREAD

**Issue by ifishball** [zw963/asuswrt-merlin-transparent-proxy#29]
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17426  100 17426    0     0  14308      0  0:00:01  0:00:01 --:--:-- 14318
cut: illegal option -- z
usage: cut -b list [-n] [file ...]
       cut -c list [file ...]
       cut -f list [-s] [-d delim] [file ...]
cut: illegal option -- z
usage: cut -b list [-n] [file ...]
       cut -c list [file ...]
       cut -f list [-s] [-d delim] [file ...]
./ss+dnsmasq: line 512: export: `=': not a valid identifier
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1357k  100 1357k    0     0   9569      0  0:02:25  0:02:25 --:--:--  9854
`$target' variable must be provided in your's scripts before detect_target.
e.g. target=localhost or target=root@123.123.123.123

**Comment by zw963** [comment]
please format you output, thanks

**Comment by ifishball** [comment]
MacOs 系统下，执行 ./ss+dnsmasq admin@192.168.1.1 后：
打印的内容如下：
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15357  100 15357    0     0   7384      0  0:00:02  0:00:02 --:--:--  7383
cut: illegal option -- z
usage: cut -b list [-n] [file ...]
       cut -c list [file ...]
       cut -f list [-s] [-d delim] [file ...]
cut: illegal option -- z
usage: cut -b list [-n] [file ...]
       cut -c list [file ...]
       cut -f list [-s] [-d delim] [file ...]
./ss+dnsmasq: line 512: export: `=': not a valid identifier
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1357k  100 1357k    0     0  39653      0  0:00:35  0:00:35 --:--:-- 27809
`$target' variable must be provided in your's scripts before detect_target.
e.g. target=localhost or target=root@123.123.123.123

**Comment by ifishball** [comment]
我用了：
https://raw.githubusercontent.com/zw963/deployment_bash/master/deploy_start.sh
也是如此

**Comment by zw963** [comment]
你原样贴出来啊,
三个反引号开头，同样的三个反引号结尾，中间原样粘贴所有 terminal 的输出。


2017年8月20日 下午5:55，"fishball" <notifications@github.com>写道：

**Comment by ifishball** [comment]
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15357  100 15357    0     0   7384      0  0:00:02  0:00:02 --:--:--  7383
cut: illegal option -- z
usage: cut -b list [-n] [file ...]
       cut -c list [file ...]
       cut -f list [-s] [-d delim] [file ...]
cut: illegal option -- z
usage: cut -b list [-n] [file ...]
       cut -c list [file ...]
       cut -f list [-s] [-d delim] [file ...]
./ss+dnsmasq: line 512: export: `=': not a valid identifier
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1357k  100 1357k    0     0  39653      0  0:00:35  0:00:35 --:--:-- 27809
`$target' variable must be provided in your's scripts before detect_target.
e.g. target=localhost or target=root@123.123.123.123
```

**Comment by ifishball** [comment]
会不会是目前使用的是Zsh的原因？

**Comment by ifishball** [comment]
不好意思，close 掉吧。应该是我前面的某个步骤有问题。

**Comment by zw963** [comment]
不确定，你可以 sh -x  ./ss+dnsmasq admin@192.168.1.1，输出内容会很长，你可以只贴出错那一部分。

**Comment by zw963** [comment]
可以了？ Mac 下没试过

2017年8月20日 下午6:21，"fishball" <notifications@github.com>写道：
