### ISSUE TITLE
需要增加个wget判断

### ISSUE THREAD

**Issue by chenDoInG** [zw963/asuswrt-merlin-transparent-proxy#3]
1.下载accelerated-domains.china.conf时如果电脑上没有wget 是不会有任何提示的。
然后push到路由器上时就会出错，路由器能ping通，电脑无法上网。
2. mac下执行sed -r会报错
sed: illegal option -- r

**Comment by zw963** [comment]
非常抱歉给你带来困扰!

这只是本人实验性的脚本, 可能存在诸多不足, 谢谢指正.
