### ISSUE TITLE
git clone github仓库时速度非常慢

### ISSUE THREAD

**Issue by ohmyarch** [zw963/asuswrt-merlin-transparent-proxy#30]
多数情况速度只有几十KB/s

**Comment by zw963** [comment]
这真不是我的问题, 是你的网络问题.

**Comment by ohmyarch** [comment]
慢是因为没走代理 难道github在白名单里面？

**Comment by ohmyarch** [comment]
没走代理难道会和我的网络有关？这只和路由器那边的规则有关吧

**Comment by zw963** [comment]
哦，理解错了，我明天查下，github 应该肯定不在国内白名单，你用哪个脚本部署的，带 chinadns 吗？如果用的这个，github
没有被强，的确可能直连

2017年8月24日 上午12:25，"Michael Yang" <notifications@github.com>写道：

**Comment by ohmyarch** [comment]
ss+dnsmasq+chinadns

**Comment by zw963** [comment]
你有没有格式化后拿另一个部署试一下？

2017年8月24日 上午8:52，"Michael Yang" <notifications@github.com>写道：

**Comment by ohmyarch** [comment]
用第一种的话访问一些国内站有问题，我最开始就用的第一种。换第二种之后基本没什么问题了，就发现这个github龟速

**Comment by zw963** [comment]
@ohmyarch , 麻烦问下, 如果不用任何脚本, 直连访问 github 如何?

如果不用访问很快, 那就是我这个脚本有问题!

**Comment by ohmyarch** [comment]
就是直连慢，我没说脚本有问题，就是想请教一下对于这种没被墙直连又慢的有没有什么好方法处理

**Comment by zw963** [comment]
可以尝试把 github 的 ip 地址加入 chinadns 黑名单?

```sh
 -l IPLIST_FILE        path to ip blacklist file
```

文件就是这个:

```sh
/opt/etc/chinadns_iplist.txt
```

**Comment by zw963** [comment]
不过其他网站仍然有问题,  你没发现用 `ss+dnsmasq+chinadns`, 很多国外网站都很慢吗?

可能还是某些配置有问题吧, 毕竟, 就算 github 的域名可以被 114 解析, 内容仍旧应该走代理的.

我常看 Youtube, 不常上国内的视频网站, 所以, 我基本上在用 `ss+dnsmasq`, chinadns 这个
脚本可能有问题.

**Comment by zw963** [comment]
@ohmyarch ,  你可以格式化 jffs 分区, 用新的脚本重新部署测试一下.

**Comment by ohmyarch** [comment]
我重新部署了脚本, 然后现在网都不能上了..
开始还能连接 国内站能上 其他不能上 过一会全部都不能上了 路由器设置页面也打不开 断开重连连不上 ssh也连不上 手机wifi连不上 挂的很彻底

这里是部署脚本时的输出：https://hastebin.com/ucurilolav

**Comment by zw963** [comment]
@ohmyarch , 不好意思, 昨晚上 U 盘烧坏了, 没做充分测试.

你再试下.

**Comment by ohmyarch** [comment]
重新部署了脚本 路由器设置页面可以正常打开了 ssh连接有线连接和wifi连接也正常了 刚重启的时候还能上国内站 youtube和twitter的页面加载非常慢基本只能显示文字出来 样式和图片都没有 过一会又是所有的站都上不去了 另外部署的时候还是有以下错误：
insmod: can't insert '/lib/modules/2.6.36.4brcmarm/kernel/net/netfilter/ipset/ip_set.ko': File exists
insmod: can't insert '/lib/modules/2.6.36.4brcmarm/kernel/net/netfilter/ipset/ip_set_hash_ip.ko': File exists
--2017-08-26 14:30:45--
 http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest
Resolving ftp.apnic.net... failed: Name or service not known.
wget: unable to resolve host address 'ftp.apnic.net'

**Comment by ohmyarch** [comment]
固件是最新的 今天才升级的 服务器那边也确定没问题

**Comment by zw963** [comment]
> insmod: can't insert '/lib/modules/2.6.36.4brcmarm/kernel/net/netfilter/ipset/ip_set.ko': File exists
> insmod: can't insert '/lib/modules/2.6.36.4brcmarm/kernel/net/netfilter/ipset/ip_set_hash_ip.ko': File exists

这个不是错误.



> --2017-08-26 14:30:45--
> http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest
> Resolving ftp.apnic.net... failed: Name or service not known.
> wget: unable to resolve host address 'ftp.apnic.net'

这个貌似是 bug, 应该修复了.

你试着在路由器里面执行下面的命令:

```sh
#  重新执行那个失败的命令.
$: /opt/etc/update_ip_whitelist
# 然后重启 chinadns 服务.
$: /opt/etc/init.d/S56chinadns restart
```

再试试效果.

**Comment by ohmyarch** [comment]
不行还是什么网站都上不了，chinadns这种你有没有自己试过？

**Comment by ohmyarch** [comment]
这应该是有bug，我之前一直跟commit修改路由器上相关的文件，就最近几天没跟，问题应该出在近几天的commit上

**Comment by zw963** [comment]
> 不行还是什么网站都上不了，chinadns这种你有没有自己试过？

我刚刚试过, 貌似部署貌似的确不能用, 需要重启后, 等几分钟才可以. :smiley: 

因为我更新了 chinadns 白名单, 也就是下面的命令输出七千多个 ip, 而原来只有四千个.
所以, chinadns 起动速度会慢些.

```sh
cat /opt/etc/chinadns_chnroute.txt |wc -l
7977
```

**Comment by ohmyarch** [comment]
基本确定是最近对iptables.sh的更改导致udp转发出了问题从而导致dns查询失败，请检查一下。顺便我的路由器型号是AC68U

**Comment by zw963** [comment]
@ohmyarch , 我在 AC66U, AC5300 完整测试了一遍, 没有问题.

你是不是没有升级到最新的梅林 380.68 ?

老的梅林, 内核模块存在, 但是好像没有开启.

**Comment by ohmyarch** [comment]
是最新的380.68

**Comment by zw963** [comment]
我刚刚又测试了一次, 而且是用长城宽带, 没有问题.

事实上, 只要部署完成, 立刻在命令行下,

```sh
$: dig www.youtube.com
; <<>> DiG 9.10.5-P3 <<>> www.youtube.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 11179
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;www.youtube.com.		IN	A

;; ANSWER SECTION:
www.youtube.com.	86399	IN	CNAME	youtube-ui.l.google.com.
youtube-ui.l.google.com. 299	IN	A	216.58.199.14

;; Query time: 334 msec
;; SERVER: 192.168.50.1#53(192.168.50.1)
;; WHEN: Fri Sep 01 21:55:59 HKT 2017
;; MSG SIZE  rcvd: 94

```

就可以返回正确的结果.

你的是什么结果?

**Comment by ohmyarch** [comment]
部署后，立即
```zsh
dig www.youtube.com

; <<>> DiG 9.11.2 <<>> www.youtube.com
;; global options: +cmd
;; connection timed out; no servers could be reached
```

这是部署时的系统日志：https://paste.ubuntu.com/25455589/

**Comment by zw963** [comment]
> 这是部署时的系统日志：https://paste.ubuntu.com/25455589/

这个日志看不出问题来, 你有没有格式化后重新部署?

可以看看部署时, 终端的日志.

同时检查:

- /opt/etc/shadowsocks.json 是否有错.
- 把 iptables.sh 替换为老的版本, 重启是否有效.

老的版本在这里:
https://github.com/zw963/asuswrt-merlin-transparent-proxy/blob/57c1aafd0fa14980dc445eb14fce7b713ecb4d5d/route/opt/etc/iptables.sh

**Comment by zw963** [comment]
脚本更新了, 采用新的实现方式了.

有空你可以格式化 jffs 重新部署一下.

如果有问题, 我再开 issue.
