### ISSUE TITLE
使用centos7 可以ssh 路由器ASUS AC88U（ARM7）。已经配置正确配置opkg，执行命令出现如下提示。

### ISSUE THREAD

**Issue by AxIauk** [zw963/asuswrt-merlin-transparent-proxy#33]
[root@Centos7 asuswrt-merlin-transparent-proxy-master]# ./ss+dnsmasq+chinadns axiauk@192.168.1.1
sh: rsync: not found
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: remote command not found (code 127) at io.c(605) [sender=3.0.9]
rsync is not installed in remote host, fallback to use scp command.
foreign_domains.conf                                                                                                                  100%   33     0.0KB/s   00:00
iptables.sh                                                                                                                           100% 2688     2.6KB/s   00:00
iptables_disable.sh                                                                                                                   100% 1290     1.3KB/s   00:00
patch_dnsmasq                                                                                                                         100%  451     0.4KB/s   00:00
restart_dnsmasq                                                                                                                       100%   84     0.1KB/s   00:00
update_dns_whitelist                                                                                                                  100%  449     0.4KB/s   00:00
update_ip_whitelist                                                                                                                   100%  359     0.4KB/s   00:00
shadowsocks.json                                                                                                                      100%  187     0.2KB/s   00:00
S22ss-tunnel                                                                                                                          100%  261     0.3KB/s   00:00
localips                                                                                                                              100%  101     0.1KB/s   00:00
./ss+dnsmasq+chinadns:行34: opkg: 未找到命令
必须首先运行 entware-setup.sh 初始化包管理系统.
[root@Centos7 asuswrt-merlin-transparent-proxy-master]# sh: rsync: not found
-bash: sh:: 未找到命令
[root@Centos7 asuswrt-merlin-transparent-proxy-master]# rsync: connection unexpectedly closed (0 bytes received so far) [sender]
-bash: 未预期的符号 `(' 附近有语法错误
[root@Centos7 asuswrt-merlin-transparent-proxy-master]# rsync error: remote command not found (code 127) at io.c(605) [sender=3.0.9]
-bash: 未预期的符号 `(' 附近有语法错误
[root@Centos7 asuswrt-merlin-transparent-proxy-master]# rsync is not installed in remote host, fallback to use scp command.

**Comment by AxIauk** [comment]
为什么没有一个在路由器上一键安装配置脚本呢？
我在路由器上 opkg install rsync 后再重试，提示如下。

rsync: This rsync lacks old-style --compress due to its external zlib.  Try -zz.
rsync error: syntax or usage error (code 1) at main.c(1567) [server=3.1.2]
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(605) [sender=                                                                                        3.0.9]

**Comment by zw963** [comment]
> ./ss+dnsmasq+chinadns:行34: opkg: 未找到命令
> 必须首先运行 entware-setup.sh 初始化包管理系统.

你有没有先进路由器, 运行 `entware-setup.sh` 初始化 entware 包管理系统?

**Comment by zw963** [comment]
> 我在路由器上 opkg install rsync 后再重试，提示如下。

不是 rsync 的问题, 该复制的文件, 已经复制上去了 ... 
你把 rsync 卸掉吧. 就用 rsyc, 或者初始化, 重头再来一次.

**Comment by AxIauk** [comment]
重新恢复出厂设置，梅林自带的entware-setup.sh 初始化安装完全正常（使用的etx3格式）。但脚本依然提示：opkg: 未找到命令。
无奈手动 opkg isntall shadowsocks-libev。网上搜了个不全面的教程，国内外分流可以用。但是DNS不完美，也不会配置dnsmasq. 也不知道dnsmasq与ipset是否兼容。
兄弟能不能脱离脚本，给初学者写个简单的教程？

**Comment by zw963** [comment]
> 重新恢复出厂设置，梅林自带的entware-setup.sh 初始化安装完全正常（使用的etx3格式）。但脚本依然提示：opkg: 未找到命令。

这点太奇怪啦. 我 README 写的已经够详细啦, 你有仔细看吗?



> 但是DNS不完美，也不会配置dnsmasq. 也不知道dnsmasq与ipset是否兼容。

最近正在弄用 ss-redir 实现 数据+dns 的自动分流, 你可以试下 udp_relay 的 
ss+dnsmasq+udprelay 脚本.

**Comment by zw963** [comment]
很多地方我也不懂, https://github.com/shadowsocks/shadowsocks-libev/issues/1666 正在讨论呢, 你有兴趣可以看看.
