### ISSUE TITLE
ss+udprelay脚本执行错误

### ISSUE THREAD

**Issue by gitx6** [zw963/asuswrt-merlin-transparent-proxy#37]
脚本执行后显示信息如下：

./ss+udprelay: 3: eval: Syntax error: "(" unexpected

然后脚本退出。

**Comment by zw963** [comment]
感觉这是是你自己修改出错了？ 版本是不是 0.3.6 ?

```sh
self="$(curl -sS https://raw.githubusercontent.com/zw963/deployment_bash/v0.3.6/deploy_start.sh)" && eval "$self"
```

**Comment by nautiluschan** [comment]
./ss+chinadns: 3: eval: Syntax error: "(" unexpected

**Comment by zw963** [comment]
今晚上回去部署试一下，稍后

2017年9月17日 下午12:50，"NautilusChan" <notifications@github.com>写道：

**Comment by zw963** [comment]
我这里使用 Linux 部署，看样子没什么问题，宿主机是 Mac ??  @wangxin6 , @NautilusChan

明天有空再试。

**Comment by nautiluschan** [comment]
我手上没有Linux机器，我通过两种方案测试的：
1)Ubuntu 17.04 liveCD
2)win10 bash，即内置的Linux子系统
测试结果一样。
与环境变量有关？我对bash不是很了解，还望多多帮助？能否换个写法，我再试试？谢谢！

**Comment by nautiluschan** [comment]
是否可以先将deploy_start.sh下载到本地，然后直接用cat?
self=eval cat deploy_start.sh?

**Comment by zw963** [comment]
试试
self=\`curl -sS https://raw.githubusercontent.com/zw963/deployment_bash/v0.3.6/deploy_start.sh\` && eval "$self"

**Comment by gitx6** [comment]
在Ubuntu 16.04 LTS上部署

self="$(curl -sS https://raw.githubusercontent.com/zw963/deployment_bash/v0.3.6/deploy_start.sh)" && eval "$self"
bash: export: deploy_start=-f deploy_start: not a function

self=curl -sS https://raw.githubusercontent.com/zw963/deployment_bash/v0.3.6/deploy_start.sh && eval "$self"
-sS: command not found

**Comment by zw963** [comment]
晕了，你以前部署不是没这个问题吗？重装过系统吗？你是最近才出现的？

给发个 backtrace 吧，在脚本的不同地方里加个 `set -x`，看看输出是哪一行挂了。

2017年9月18日 上午8:44，"wangxin6" <notifications@github.com>写道：

在Ubuntu 16.04 LTS上部署

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/zw963/asuswrt-merlin-transparent-proxy/issues/37#issuecomment-330106104>,
or mute the thread

**Comment by gitx6** [comment]
母鸡没做任何升级和改动。

##only support define a bash variable, bash array variable not supported.
function __export () {
    local name=$(echo "$*" |cut -d'=' -f1)
    local value=$(echo "$*" |cut -d'=' -f2-)
    local escaped_value=$(echo "$value" |sed 's#\([\$"\`]\)#\\\1#g')
    eval 'builtin export $name="$value"'
    export_hooks="$export_hooks builtin export $name=\"$escaped_value\""
}

alias export=__export
./ss+udprelay: 3: eval: Syntax error: "(" unexpected

**Comment by zw963** [comment]
试下最新的 master.

**Comment by nautiluschan** [comment]
`2017-09-18 18:20:49 (38.6 KB/s) - '/opt/etc/dnsmasq.d/accelerated-domains.china.conf.bak' saved [1394219/1394219]

cat: can't open '/opt/etc/user_domain_name_whitelist.txt': No such file or directory
dnsmasq: syntax check OK.
 Shutting down chinadns...              done.
 Starting chinadns...              done.
Applying iptables rule, it may take several minute to finish ...
ss-redir not enable udp redir, skip UDP rule.
貌似部署成功了!`

`admin@R8000-3AB7:/jffs/scripts# ./services-start
 Starting haveged...              done.
 Starting ss-redir...              done.
 Starting ss-tunnel...              done.
 Starting chinadns...              done.
 Starting transmission-daemon...              done.
cat: can't open '/opt/etc/user_domain_name_whitelist.txt': No such file or directory
dnsmasq: syntax check OK.
 Shutting down chinadns...              done.
 Starting chinadns...              done.
iptables: Chain already exists.`

无法启动

**Comment by nautiluschan** [comment]
ss+chinadns安装成功，但是显示“ can't open '/opt/etc/user_domain_name_whitelist.txt'”，好像导致dnsmasq未启动，plus.google.com无法打开，显示"找不到 plus.google.com 的服务器 DNS 地址。"
还烦请看看如何修复？谢谢！ @zw963

**Comment by zw963** [comment]
> ss+chinadns安装成功，但是显示“ can't open '/opt/etc/user_domain_name_whitelist.txt'”，好像导致dnsmasq未启动，plus.google.com无法打开，显示"找不到 plus.google.com 的服务器 DNS 地址。"
> 还烦请看看如何修复？谢谢！ @zw963

b6209cc 已经修复， @NautilusChan , 你最好看下 [Wiki](https://github.com/zw963/asuswrt-merlin-transparent-proxy/wiki) 再部署， `opt/etc/user_domain_name_whitelist.txt` 是域名白名单。想直连的域名可以加进来。

**Comment by nautiluschan** [comment]
非常感谢！已经配置好。
另外想请教一下，是不是因为win10bash 的关系，还是你们都是用key登录，在安装过程中，我需要输入10多次密码，基本上执行一行输入一次。

**Comment by zw963** [comment]
我们配置了 key 免密登录

2017年9月18日 下午10:54，"NautilusChan" <notifications@github.com>写道：
