### ISSUE TITLE
dnscrypt-proxy.sh文件缺失

### ISSUE THREAD

**Issue by wishWinds** [zw963/asuswrt-merlin-transparent-proxy#38]
`copy route/opt/etc/dnscrypt-proxy.sh /opt/etc`

1. 其中dnscrypt-proxy.sh文件缺失。
2. 在使用第三种方法“ss+dnsmasq+dnscrypt”。服务器端同样应该安装dnscrypt。应当如何配置呢？

**Comment by zw963** [comment]
这个文件让你自己加的. 

示例:
```
# /opt/etc/dnscrypt-proxy.sh

resolver_address_with_port='123.123.123.123:22335'
provider_name='2.dnscrypt-cert.domain.com'
provider_key='3750:AED7:CEAB:DA91:137A:AFCD:3330:AEAA:2FEB:22AB:07FB:KVCE:3E72:31A3:5F1E:FE78'
```

> 在使用第三种方法“ss+dnsmasq+dnscrypt”。服务器端同样应该安装dnscrypt。应当如何配置呢？

我这个是用自己的服务器的方案，暂时没有提供远程部署脚本，你可以搜索下 dnscrypt-wrapper, 有很多教程。
