### ISSUE TITLE
ac68u merlin380.63_2 无法使用ipset

### ISSUE THREAD

**Issue by chenDoInG** [zw963/asuswrt-merlin-transparent-proxy#4]
需要检查是否有xt_set模块，否则无法运行。

[bug：Sets generated by ipset 6.x cannot be accesed by iptables](https://github.com/RMerl/asuswrt-merlin/issues/1062)
需要执行脚本如下：
\# Load ipset modules
ipset -v | grep -i "v4" > /dev/null 2>&1
if [ $? -eq 0 ];
then
   \# old ipset
   ipsetv=4
   lsmod | grep "ipt_set" > /dev/null 2>&1 || \
   for module in ip_set ip_set_nethash ip_set_iphash ipt_set
   do
       insmod $module
   done
else
   \# new ipset
   ipsetv=6
   lsmod | grep "xt_set" > /dev/null 2>&1 || \
   for module in ip_set ip_set_hash_net ip_set_hash_ip xt_set
   do
       insmod $module
   done
fi

**Comment by smthvitas** [comment]
超级棒，It works！
之前一直提示“No chain/target/match by that name”

顺便问下，怎么找出来是这个原因的？我这完全没有头绪~

**Comment by zw963** [comment]
@chenDoInG , 我还没用过 AC68U 那么高端的路由器. : (

你的脚本我做了一点点简化, 排版, 照样全收, 有空请帮忙测试下, 非常感谢.

**Comment by zw963** [comment]
@chenDoInG ,  之前直接拷贝你的代码进来不工作, 我重构了代码, 经过在 AC87U 上面测试, 工作的很好.

你可以在测试下, 有问题, 请提 issue.
