### ISSUE TITLE
ss+udprelay脚本执行退出

### ISSUE THREAD

**Issue by gitx6** [zw963/asuswrt-merlin-transparent-proxy#40]
脚本执行在下面步骤时退出。

echo '\''***********************************************************'\''
echo Remote deploy scripts is started !!
echo '\''***********************************************************'\''
set -ue
'
+ '[' -z '' ']'
+ set -u
+ ssh admin@192.168.1.1 bash --version
admin@192.168.1.1's password: 
+ '[' 0 == 127 ']'
+ ssh admin@192.168.1.1 bash
admin@192.168.1.1's password: 
***********************************************************
Remote deploy scripts is started !!
***********************************************************
+ exit 0

**Comment by zw963** [comment]
这个可能是 Mac 的问题??

**Comment by gitx6** [comment]
在Ubuntu 16.04 LTS上部署

**Comment by zw963** [comment]
这个问题可能和 Mac 下是同一个问题，有没有试试其他脚本？例如：ss+dnsmasq+dnscrypt，这个是效果最好的，需要自己部署 dnscrypt-wrapper

**Comment by zw963** [comment]
测试下最新的安装包, mac 下面应该也可以了.

**Comment by gitx6** [comment]
安装失败。。。。

echo '\''***********************************************************'\''
echo Remote deploy scripts is started !!
echo '\''***********************************************************'\''
set -ue
'
+ '[' -z '' ']'
+ set -u
+ ssh admin@192.168.1.1 bash -c '"perl' '--version"'
+ '[' 127 == 127 ']'
+ echo 'remote host missing bash/perl, try to install it...'
remote host missing bash/perl, try to install it...
+ ssh admin@192.168.1.1 'opkg install bash perl'
Collected errors:
 * opkg_install_pkg: Package perl md5sum mismatch. Either the opkg or the package index are corrupt. Try 'opkg update'.
 * opkg_install_cmd: Cannot install package perl.
Package bash (4.3.42-1a) installed in root is up to date.
Installing perl (5.24.1-1) to root...
Downloading http://pkg.entware.net/binaries/armv7/perl_5.24.1-1_armv7soft.ipk
+ ssh admin@192.168.1.1 bash
***********************************************************
Remote deploy scripts is started !!
***********************************************************
+ exit 0

**Comment by gitx6** [comment]
在路由器手动运行opkg update 和opkg install bash perl后，脚本仍然无法运行

echo '\''***********************************************************'\''
echo Remote deploy scripts is started !!
echo '\''***********************************************************'\''
set -ue
'
+ '[' -z '' ']'
+ set -u
+ ssh admin@192.168.1.1 bash -c '"perl' '--version"'
+ '[' 0 == 127 ']'
+ ssh admin@192.168.1.1 bash
***********************************************************
Remote deploy scripts is started !!
***********************************************************
+ exit 0

**Comment by zw963** [comment]
你是不是用的 dash，Ubuntu系统默认是这个。

命令行下 echo $0

**Comment by gitx6** [comment]
$ echo $0
bash

**Comment by zw963** [comment]
你以前不是至少可以开始部署么？感觉你的电脑有问题，你是不是加了什么 set 设定

**Comment by gitx6** [comment]
没有改过任何配置。。。

我现在重装一遍虚拟机再试一次。。。。

**Comment by zw963** [comment]
麻烦装个虚拟机试试了，我改天也装个 16.04 试试

**Comment by gitx6** [comment]
你现在用的是什么？要不我安装一个和你 一样的系统。。。

**Comment by zw963** [comment]
我用的系统小众了点，slackware，但是，我真觉得是你自己改了什么我bash 默认配置，我 Mac 下都可以部署了

**Comment by gitx6** [comment]
重装ubuntu以后，问题依旧。

**Comment by lniwn** [comment]
会不会是远程脚本里的某个url访问超时？依次用curl试试呢？

**Comment by zw963** [comment]
issue 太久了, 不确定问题, 有问题请重新提 issue.

**Comment by gitx6** [comment]
Oracle VM VirtualBox 5.2.6 + Debian 9.3.0 部署成功

**Comment by zw963** [comment]
@wangxin6 , Cool
