### ISSUE TITLE
部署脚本后opkg无法更新/升级/装包

### ISSUE THREAD

**Issue by ohmyarch** [zw963/asuswrt-merlin-transparent-proxy#41]
使用的方案是ss+chinadns+dnscrypt

执行
```zsh
opkg update
```
报错如下：
```zsh
Downloading http://pkg.entware.net/binaries/armv7/Packages.gz
*** Failed to download the package list from http://pkg.entware.net/binaries/armv7/Packages.gz

Collected errors:
 * opkg_download: Failed to download http://pkg.entware.net/binaries/armv7/Packages.gz, wget returned 4.
 * opkg_download: Check your network settings and connectivity.
```

部署脚本之前没有问题

**Comment by zw963** [comment]
看 Wiki，需要加白名单域名和IP

**Comment by ohmyarch** [comment]
建议自带一个白名单，opkg这类默认就在白名单里。不然一部署完opkg就不能用了，还要加什么白名单，这不好吧

**Comment by zw963** [comment]
@ohmyarch ,  白名单可以加, 但是最近发现问题其实不在白名单上, 因为即使不加白名单, 也应该可以用 opkg 才对.

我刚刚试了下, 找到文件 `/opt/etc/init.d/S09dnscrypt-proxy`, 然后打开文件, 把那个 
```
ARGS="-T -a 127.0.0.1:65053 -r 103.16.228.84:22335 ... /tmp/dnscrypt-proxy.log"
```

里面的  '-T' 手动删除, 然后 `/opt/etc/init.d/S09dnscrypt-proxy restart`, 然后再试试 opkg 是不是
可以工作. (在没有指定白名单的情况下).

我刚才试过了, 可以.  :smile:

**Comment by zw963** [comment]
事实上, 去掉了 `-T` 参数,  dnsmasq 的 dns 缓存功能也能用了, 例如你查一次 Google, 一段时间内, 不需要通过 dnscrypt 再次远程查询了.

只是, 之前有段时间, 不加 -T, 貌似有点不稳定, 但也不确定是不是宽带自己的问题, 可以肯定的是, 后来加了  -T, 换了个宽带, 最近速度一直很不错, 可以说相当爽. 但是, 确定就是 `wget` 之类的工具, 在 docker 下, 在路由器里面不可用, 这是个大问题, 我在考虑去掉 -T 试试.

**Comment by ohmyarch** [comment]
ss+chinadns+dnscrypt这个方案本来就没有-T啊

**Comment by zw963** [comment]
默认白名单已加。
