### ISSUE TITLE
ss+chinadns执行脚本退出

### ISSUE THREAD

**Issue by reepool** [zw963/asuswrt-merlin-transparent-proxy#43]
Mac 10.13.1下运行ss+chinadns，报『bash: syntax error: unexpected "("』退出。有没有调试信息可看，不知道是在哪一步退的。

**Comment by zw963** [comment]
可以尝试添加个 set -x输出更多信息

**Comment by reepool** [comment]
我在脚本开始加了set +x，运行返回结构如下：
++ curl -sS https://raw.githubusercontent.com/zw963/deployment_bash/v0.3.7/deploy_start.sh
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to raw.githubusercontent.com:443 
+ self=
+ export target=reepool@192.168.100.100
+ target=reepool@192.168.100.100
+ '[' '!' -e ./route/opt/etc/shadowsocks.json ']'
+ copy route/opt/etc/dnsmasq.d/foreign_domains.conf /opt/etc/dnsmasq.d/foreign_domains.conf
./ss+chinadns: line 16: copy: command not found
+ copy route/opt/etc/iptables.sh /opt/etc
./ss+chinadns: line 17: copy: command not found
+ copy route/opt/etc/toggle_proxy.sh /opt/etc
./ss+chinadns: line 18: copy: command not found
+ copy route/opt/etc/patch_dnsmasq /opt/etc
./ss+chinadns: line 19: copy: command not found
+ copy route/opt/etc/restart_dnsmasq /opt/etc
./ss+chinadns: line 20: copy: command not found
+ copy route/opt/etc/shadowsocks.json /opt/etc
./ss+chinadns: line 21: copy: command not found
+ copy route/opt/etc/init.d/S22ss-tunnel /opt/etc/init.d
./ss+chinadns: line 22: copy: command not found
+ copy route/opt/etc/localips /opt/etc
./ss+chinadns: line 23: copy: command not found
+ copy route/opt/etc/update_ip_whitelist /opt/etc
./ss+chinadns: line 24: copy: command not found
+ '[' -e route/opt/etc/user_ip_whitelist.txt ']'
+ copy route/opt/etc/user_ip_whitelist.txt /opt/etc
./ss+chinadns: line 26: copy: command not found
+ '[' -e route/opt/etc/user_domain_name_whitelist.txt ']'
+ copy route/opt/etc/user_domain_name_whitelist.txt /opt/etc
./ss+chinadns: line 27: copy: command not found
+ deploy_start
./ss+chinadns: line 29: deploy_start: command not found
+ /opt/etc/toggle_proxy.sh disable
./ss+chinadns: line 31: /opt/etc/toggle_proxy.sh: No such file or directory
+ opkg update
./ss+chinadns: line 42: opkg: command not found
+ echo 'Run `opkg update'\'' failed.'
Run `opkg update' failed.
+ echo 'Run `entware-setup.sh'\'' to initalize entware-ng!'
Run `entware-setup.sh' to initalize entware-ng!
+ exit
麻烦看看是什么原因，谢谢啦。
该拷贝的配置文件和脚本我都手工拷到相应目录了，copy失败应该不打紧。

**Comment by zw963** [comment]
但是日志里这里面没有前一条错误输出啊。

2017年11月16日 上午12:10，"reepool" <notifications@github.com>写道：

**Comment by zw963** [comment]
刚刚在本地路由器上部署了下 `ss+dnsmasq+dnscrypt`, 没发现任何问题, 一次成功.

你为什么连  opkg 命令都没有, 有没有查看项目 [Wiki](https://github.com/zw963/asuswrt-merlin-transparent-proxy/wiki)??
