### ISSUE TITLE
How do install SS  on the ASUS Merlin Router

### ISSUE THREAD

**Issue by alim240** [zw963/asuswrt-merlin-transparent-proxy#44]
Hi . i  have ASUS AC68U router and Merlin FW-382.
I don't understand how to install SS to route.

**Comment by zw963** [comment]
https://github.com/zw963/asuswrt-merlin-transparent-proxy/blob/master/ss%2Bdnsmasq%2Bdnscrypt#L57-L61

**Comment by alim240** [comment]
Thank you~!
