### ISSUE TITLE
ss+chinadns 部署失败

### ISSUE THREAD

**Issue by johnny007356** [zw963/asuswrt-merlin-transparent-proxy#47]
./ss+chinadns admin@192.168.50.1
rsync is not installed in remote host, fallback to use scp command.
foreign_domains.conf                          100%   34     0.0KB/s   00:00    
iptables.sh                                   100% 5264     5.1KB/s   00:00    
toggle_proxy.sh                               100% 1211     1.2KB/s   00:00    
patch_router                                  100% 1812     1.8KB/s   00:00    
restart_dnsmasq                               100%   84     0.1KB/s   00:00    
shadowsocks.json                              100%  164     0.2KB/s   00:00    
S22ss-tunnel                                  100%  261     0.3KB/s   00:00    
localips                                      100%  265     0.3KB/s   00:00    
update_ip_whitelist                           100%  528     0.5KB/s   00:00    
remote host missing bash/perl, try to install it...
Installing bash (4.4.12-1) to root...
Downloading http://bin.entware.net/armv7sf-k2.6/bash_4.4.12-1_armv7-2.6.ipk
Installing libncurses (6.1-1) to root...
Downloading http://bin.entware.net/armv7sf-k2.6/libncurses_6.1-1_armv7-2.6.ipk
Installing libncursesw (6.1-1) to root...
Downloading http://bin.entware.net/armv7sf-k2.6/libncursesw_6.1-1_armv7-2.6.ipk
Installing perl (5.26.1-3) to root...
Downloading http://bin.entware.net/armv7sf-k2.6/perl_5.26.1-3_armv7-2.6.ipk
Configuring libncursesw.
Configuring libncurses.
Configuring bash.
Configuring perl.
***********************************************************
Remote deploy scripts is started !!
***********************************************************
Disable proxy ...
ipset v6.32: The set with the given name does not exist
iptables: No chain/target/match by that name.
iptables: No chain/target/match by that name.
dnsmasq: syntax check OK.
Done.

**Comment by zw963** [comment]
你的日志是否输出不完整?

感觉好像过早地结束了, 根本没开始部署.

**Comment by zw963** [comment]
不知道为什么, 你部署时, 在运行了 `/opt/etc/toggle_proxy.sh disable` 之后就意外退出了.

你可以以下两个办法试一下:

- 使用最新的 0.3 release 分支
- 如果还不行, 浏览器格式化 jffs, 再来一次.

**Comment by johnny007356** [comment]
感谢耐心回复。
第一次运行./ss+chinadns是可以一直运行下去得，但是运行后无法翻墙。
再次运行就一直是上面得日志了，初始化jffs后还是不行。
后来根据脚本命令，手工部署了后就可以翻墙了。
最近比较忙，回复信息晚了，不好意思。
再次感谢您做了这个项目。
