### ISSUE TITLE
remote host missing bash/perl

### ISSUE THREAD

**Issue by gitx6** [zw963/asuswrt-merlin-transparent-proxy#48]
重新部署提示错误后退出:

remote host missing bash/perl, try to install it...
collected errors:
 *opkg_install_cmd: Cannot install package bash.
 *opkg_install_cmd: Cannot install package bash.
Unknown package 'bash'.
Unknown package 'perl'.
sh: bash: not found

解决方案：
opkg update && opkg upgrade
opkg install bash
opkg install perl

然后重新部署

**Comment by zw963** [comment]
考虑在最开始安装 bash perl 的时候, 就先 update 一下.
