### ISSUE TITLE
missing user defined whitelist

### ISSUE THREAD

**Issue by gitx6** [zw963/asuswrt-merlin-transparent-proxy#49]
user_domain_name_whitelist.txt 和 user_ip_whitelist.txt 在v0.3版本中不再需要？

**Comment by zw963** [comment]
要啊，原来 ip 白名单功能后来改错了，失效了，因此修复了下。

这两个文件你要本地项目 router/opt/etc 内创建，再部署，才会同步上去。或者手动去路由器内自己创建，然后，运行 patch_route

**Comment by gitx6** [comment]
Thanks
