### ISSUE TITLE
ubuntu 16.04 LTS下执行脚本失败

### ISSUE THREAD

**Issue by songshupine** [zw963/asuswrt-merlin-transparent-proxy#5]
Ubutnu虚拟机下执行脚不会登陆路由，最后ubuntu机器重启。
请问作者是在什么环境下执行的脚本？

**Comment by zw963** [comment]
@songshupine , 这是华硕的路由器支持的一款定制操作系统叫做 `梅林` 的配置脚本.
你的是 Ubuntu, 它们的包管理是不一样的.

**Comment by songshupine** [comment]
我的理解是这个脚本需要在PC机的linux环境下面执行，脚本执行过程中通过ssh登录华硕的梅林系统进行处理。不知道我的理解是否对？
此脚本我在centos下可以正常运行，但ubuntu下执行有问题。

**Comment by zw963** [comment]
> 我的理解是这个脚本需要在PC机的linux环境下面执行，脚本执行过程中通过ssh登录华硕的梅林系统进行处理。不知道我的理解是否对？

对的.

但是你告诉我你的 ubuntu 主机重启了, 那么这个脚本很显然在你的主机上执行了.
有出错信息吗?

**Comment by zw963** [comment]
@songshupine , 你可以再试下,  5b42c12 可能会解决你遇到的问题.

原因可能是因为, Ubuntu 默认的 shell 解释器是 dash, 而 Centos 则是 bash.

**Comment by zw963** [comment]
更新了 README, 请详细重新读帮助, 再重试, 有问题再反馈, 谢谢.
