### ISSUE TITLE
ARM架构

### ISSUE THREAD

**Issue by gitbobo** [zw963/asuswrt-merlin-transparent-proxy#51]
在第三个选择：ss+udprelay (仅 ARM 架构支持), 只需要 ss-redir 一个命令自己全部搞定, AC68U+ 的路由器不妨用这个.  
ss-redir命令是指的哪个？在这种情况下DNS是全局通过SS么？

**Comment by gitx6** [comment]
1./ss+udprelay脚本中的第89，90行：
‘# 默认 shadowsocks 启动脚本使用 ss-redir 而不是 ss-local, 端口 1080.’
’replace_string ss-local ss-redir /opt/etc/init.d/S22shadowsocks‘

2. update_dns_whitelist 、update_ip_whitelist以及user_ip_whitelist.txt、user_domain_name_whitelist.txt外的dns查询，走UDP以防投毒。

**Comment by gitbobo** [comment]
感谢您的回答！ 
我经过centos6.9+ac66u-B1的配置没有成功实现ss+dnsmasq+dnscrypt。问题应该在SS-server上。我的ss server装了锐速,可能影响。您在SS Server上的部署脚本是否可提供？

**Comment by gitx6** [comment]
https://github.com/zw963/asuswrt-merlin-transparent-proxy/blob/master/deploy_ss_to_vps

**Comment by zw963** [comment]
@gitbobo ,  @wangxin6 贴的那个脚本是工作的, 我刚刚用这个脚本部署了一个 linde 日本机房的 VPS, 用的是 Ubuntu 16.04.

**Comment by zw963** [comment]
@gitbobo , 不过你可能需要自己假设 dnscrypt-wrapper 服务或用 public 的服务来加密 DNS
