### ISSUE TITLE
ss+udprelay失败

### ISSUE THREAD

**Issue by skiyer** [zw963/asuswrt-merlin-transparent-proxy#53]
```
$ ./ss+udprelay admin@192.168.1.1 
***********************************************************
Remote deploy scripts is started !!
***********************************************************
bash: line 589: /opt/etc/toggle_proxy.sh: No such file or directory
```

**Comment by skiyer** [comment]
所有的文件都copy失败了，手动scp过去就好了

**Comment by zw963** [comment]
什么系统? 很奇怪为什么会 copy 失败.

**Comment by koallen** [comment]
同样的错误，我是在mac上运行的脚本。

**Comment by koallen** [comment]
我简单看了一下，你是要在运行脚本的机器上把那些文件复制到/opt/etc？Mac直接就Permission denied了。为什么要做这一步呢？

**Comment by zw963** [comment]
我是要复制到路由器的该目录下，好奇怪，为何复制到你主机目录

**Comment by koallen** [comment]
我看了下你那个开头eval的那个部署的脚本，应该是用scp复制到路由器。但不知道为什么复制完路由器里没有…玄学…后来我也是自己scp的。

**Comment by zw963** [comment]
从你第一个帖子贴的内容来看, 你应该根本没有开始赋值.

方便的话,  下面的方式执行

```sh
sh -x ./ss+udprelay admin@192.168.1.1 
```

看看有啥输出.

**Comment by zw963** [comment]
this bug is fixed.

**Comment by gitx6** [comment]
scp复制失败。

sh -x ./ss+udprelay admin@192.168.1,1
最后两行代码：
alias export=_export
./ss+udprelay: 3: eval: syntax error： "(" unexpected
