### ISSUE TITLE
尝试ss+udprelay和ss+chinadns均失败

### ISSUE THREAD

**Issue by koallen** [zw963/asuswrt-merlin-transparent-proxy#55]
你好，首先感谢这么好的项目！有些问题想请教一下：

我昨天尝试部署ss+udprelay和ss+chinadns两种到我的AC68U，都不行。中间都是格式化了jffs和u盘从头再来的。我也尝试按照脚本里的命令自己执行部署（见 #47），也不可以。

我发现我手动用nslookup去通过ss-redir（或ss-tunnel）查询DNS没有任何反应，会直接timeout。nslookup查询114是没问题的。这个是怎么回事？我服务器那边开启了`-u`的选项，难道还需要什么额外的设置？

另外因为DNS解析失败，目前我还没测试DNS解析成功后连接（也就是iptables那部分）有没有问题。

P.S. 我在电脑上直接连ss-server是没问题的。

**Comment by zw963** [comment]
你的设备是 ARM 架构的吗？这几天部署了几次 ss+udprelay，没问题的，chinadns 我需要有空看下

**Comment by koallen** [comment]
AC68U是ARM的没错。我刚才又在Mac上测试，然后我意识到我服务器上防火墙没开ss端口的UDP（之前部署的时候只开了TCP）。我刚刚又重新格式化jffs部署了一遍，已经可以用了！

你觉得wiki上加一个troubleshooting的部分怎么样？可以汇集一下常见的问题。

**Comment by zw963** [comment]
> 然后我意识到我服务器上防火墙没开ss端口的UDP

这个不同的 VPS 不同, 有的默认没开防火墙, 不需要加 iptables rule 也可以.

> 你觉得wiki上加一个troubleshooting的部分怎么样？

可以啊
