### ISSUE TITLE
紧急建议

### ISSUE THREAD

**Issue by gitbobo** [zw963/asuswrt-merlin-transparent-proxy#56]
udp to tcp is better.

**Comment by zw963** [comment]
dnscrypt-proxy 自己有 tcp 方案的. 

https://github.com/zw963/asuswrt-merlin-transparent-proxy/wiki#dnscrypt-proxy-%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E7%A4%BA%E4%BE%8B

**Comment by zw963** [comment]
如果你需要 tcp, 参考 Wiki, 取消注释 tcp_only 那个注释, 就走 tcp 了, 唯一的缺点是, dnsmasq 自身提供的  dns cache 功能变得无效.
