### ISSUE TITLE
能否开启obfs?

### ISSUE THREAD

**Issue by gitbobo** [zw963/asuswrt-merlin-transparent-proxy#57]
obfs已经安装在entware中

**Comment by zw963** [comment]
不懂这个是干什么的. 如果只是为了 DNS 加密的话, 路由器的 dnscrypt-proxy + 服务器的 dnscrypt-wrapprer 目前工作的挺好的, 用 ss+dnsmasq+dnscrypt 部署, 但服务器要安装 dnscrypt-wrapper

**Comment by gitbobo** [comment]
混淆用的，使流量特征不容易被检出。

**Comment by zw963** [comment]
建议先参照 wiki 试试 dnscrypt-proxy 的 tcp 方案.
