### ISSUE TITLE
user_domain_name_blacklist.txt无法使用

### ISSUE THREAD

**Issue by gitx6** [zw963/asuswrt-merlin-transparent-proxy#61]
加入 
apple.com
amazon.com
到/opt/etc/user_domain_name_blacklist.txt后。使用./toggle_proxy.sh关闭再开启后，两个网站无法访问。
从文件中移除后，使用./toggle_proxy.sh关闭再开启后，可以正常访问。

**Comment by gitx6** [comment]
加入网站后，在/tmp/mnt/sda1/entware/etc/dnsmasq.d目录下会生成新的文件blacklist-domains.china.c
onf。内容如下：
address=/amazon.com/127.0.0.1

浏览器访问www.amazon.com，提示无法访问到页面。

**Comment by zw963** [comment]
这个项目, 针对是否要走代理, 使用的是白名单策略, 白名单里面的全部直连, 其余全部走代理.

这个新加的功能的目的就是为了设定无法访问的黑名单, 例如, 我不想让家里人上百度, 我就将 www.baidu.com 加入了黑名单. 

我承认我名字定义的不好,  我新加的 `/opt/etc/user_domain_name_blacklist.txt` 可能会带来误解.
也许你可以帮我想个好名字. :smile:

**Comment by zw963** [comment]
也许换成 `user_domain_name_blocklist.txt` 更好一些?

**Comment by gitx6** [comment]
确实block与目的更适合。

是不是可以加定时功能更新这个清单
https://github.com/pexcn/daily/blob/gh-pages/adblock/adblock_full.conf

**Comment by zw963** [comment]
> 是不是可以加定时功能更新这个清单
> https://github.com/pexcn/daily/blob/gh-pages/adblock/adblock_full.conf

你是想做广告过滤吧? 当然可以. 但是仅仅这一步是不够的, 弹出的广告页面,
我们期望的效果是完全看不到弹窗, 而不是一个返回 500 的悬浮页面.
要做到完全透明, 需要安装 pixelserv-tls, 他会返回一个透明的.

这个东西不难, 我打算有空就看看. [这里](https://diversion.ch/diversion/installation.html) 有一个
类似的项目, 我试过一次, 可以工作, 但是好像和我这个有点冲突? 没有详细看.
