### ISSUE TITLE
dnscrypt 证书失效, 导致路由器不能联网 

### ISSUE THREAD

**Issue by momobile** [zw963/asuswrt-merlin-transparent-proxy#64]
采用ss+dnsmasq+dnscrypt方案，脚本跑完，一切正常，可以实现透明代理，但是之后会出现不能上网的情况

我一共试了3次，其中最长的一次用了1天的时间，期间也感觉路由器负载很高，温度也很高，这倒是无所谓。但是最后这三次最后都出现不能上网的情况，表现就是，用着就断网，然后登陆路由发现，wan链接断开了。

路由器型号：asus rt-ac1900p

需要日志告诉我，我提供

**Comment by zw963** [comment]
是不是最近引入什么东西，搞挂了，我回去自己路由器部署试一下。

你自己有没有先恢复默认，确定是部署脚本后，才造成的这个问题？

**Comment by momobile** [comment]
有的，
第1次执行脚本，然后正常用，然后我说重启一下看看效果吧，结果导致我的路由器wifi都连不上，只能硬reset。然后重刷官方rom，再刷merlin，
开始第二次，执行完毕之后正常用了1天时间，然后又出问题，在此基础上，重刷merlin+设置重新初始化，再刷第三次。然后就又废了

**Comment by momobile** [comment]
我观察，连不上网是有一段日志的，我记录下来了，但是没有在这台电脑上。好像是nat redirect error吧类似/tmp/nat_eth0_xxx

**Comment by gitx6** [comment]
RT-AC68U目前开机8天，表示毫无压力。

**Comment by zw963** [comment]
> 有的，
> 第1次执行脚本，然后正常用，然后我说重启一下看看效果吧，结果导致我的路由器wifi都连不上，只能硬reset。然后重刷官方rom，再刷merlin，
> 开始第二次，执行完毕之后正常用了1天时间，然后又出问题，在此基础上，重刷merlin+设置重新初始化，再刷第三次。然后就又废了

执行脚本, 如果上网出了问题, 理论上, 拔掉 U 盘就可以了, 至于初始化, 真的不用每次重新刷 merlin,
相信我, 拔掉 U 盘, 重启后, 啥都会恢复成默认. 可以看 [Wiki](https://github.com/zw963/asuswrt-merlin-transparent-proxy/wiki), 我表示写的挺详细的.

**Comment by momobile** [comment]
嗯，那我找时间再试一下，把插优盘这个操作我还没有做过。对恢复上网有帮助吗？重启加把插优盘

发自我的 iPhone

在 2018年11月27日，下午10:20，Billy.Zheng <notifications@github.com<mailto:notifications@github.com>> 写道：


有的，
第1次执行脚本，然后正常用，然后我说重启一下看看效果吧，结果导致我的路由器wifi都连不上，只能硬reset。然后重刷官方rom，再刷merlin，
开始第二次，执行完毕之后正常用了1天时间，然后又出问题，在此基础上，重刷merlin+设置重新初始化，再刷第三次。然后就又废了

执行脚本, 如果上网出了问题, 理论上, 拔掉 U 盘就可以了, 至于初始化, 真的不用每次重新刷 merlin,
相信我, 拔掉 U 盘, 重启后, 啥都会恢复成默认. 可以看 Wiki<https://github.com/zw963/asuswrt-merlin-transparent-proxy/wiki>, 我表示写的挺详细的.

**Comment by FrankZhang2017** [comment]
我在Ubuntu下面，感觉有些命令格式不一致。楼主是用的MAC吗？
比如说这两个命令：
copy  ：看内容像是scp的意思
self=<b><font color="red">"$(</b>curl -sS https://raw.githubusercontent.com/zw963/deployment_bash/v0.4.6/deploy_start.sh)" && eval "$self"。 看内容像是Linux下bash中self=`curl .....`的意思

**Comment by momobile** [comment]
mac，脚本没报错

发自我的 iPhone

在 2018年11月29日，下午8:20，FrankZhang <notifications@github.com<mailto:notifications@github.com>> 写道：


我在Ubuntu下面，感觉有些命令格式不一致。楼主是用的MAC吗？
比如说这两个命令：
copy ：看内容像是scp的意思
self="$(curl -sS https://raw.githubusercontent.com/zw963/deployment_bash/v0.4.6/deploy_start.sh)" && eval "$self"。 看内容像是Linux下bash中self=curl .....的意思

**Comment by zw963** [comment]
家里的 AC66U 前天覆盖安装了一边, 至今没发现问题, 路由器无法上网, 应该与本脚本无关.

AC1900P 没有条件测试, 如果没问题, 请关掉这个 issue.

**Comment by momobile** [comment]
我今天又开始折腾了，这是执行中的一些报错，有问题吗

104) soltysiak-ipv6 ("Soltysiak over IPv6")
105) ventricle.us ("Anatomical DNS")
106) yandex ("Yandex")
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
[: echo: bad number
Configuring dnscrypt-proxy-resolvers.
Configuring libltdl.
Configuring libldns.
Configuring dnscrypt-proxy.
Installing bind-dig (9.11.3-2) to root...

**Comment by zw963** [comment]
如果你在你的服务器上部署了 dnscrypt-wrapper, 就没问题.

ss+dnsmasq+dnscrypt 方案是需要自己建立 dnscrypt server 的.

**Comment by momobile** [comment]
[: echo: bad number     我是指这个出现了很多次，有问题吗？

**Comment by momobile** [comment]
从昨天至今一切正常，昨天我发现了一个问题，我自己搭的dnscrypt服务一直就没起来，不知道之前的三次失败和这个有没有关系。

一个问题，我重启路由服务都会自启动吗？我现在不敢重启了，也不敢动路由其他设置😂

发自我的 iPhone

在 2018年12月1日，上午12:04，Billy.Zheng <notifications@github.com<mailto:notifications@github.com>> 写道：


如果你在你的服务器上部署了 dnscrypt-wrapper, 就没问题.

ss+dnsmasq+dnscrypt 方案是需要自己建立 dnscrypt server 的.

**Comment by zw963** [comment]
>> 我自己搭的dnscrypt服务一直就没起来，不知道之前的三次失败和这个有没有关系。

就这个关系.

>> 我重启路由服务都会自启动吗？我现在不敢重启了，也不敢动路由其他设置.

这个随便重启, 你改 Web 页面的设置也不影响.

**Comment by momobile** [comment]
OK，多谢，我我观察两天，没问题我来close

发自我的 iPhone

在 2018年12月1日，下午10:06，Billy.Zheng <notifications@github.com<mailto:notifications@github.com>> 写道：


我自己搭的dnscrypt服务一直就没起来，不知道之前的三次失败和这个有没有关系。

就这个关系.

我重启路由服务都会自启动吗？我现在不敢重启了，也不敢动路由其他设置.

这个随便重启, 你改 Web 页面的设置也不影响.

**Comment by momobile** [comment]
又上不了网了，登上vps看，一切正常，dnscrypt进程也在，日志也没有异常，我重启dnscrypt报这个了

[5538] 03 Dec 21:33:10.306 [err] [main.c:801] No (currently) valid certs found.

你的脚本能不能提供一个不用dnscrypt的？就是简单路由，国内走国内，国外走shadowsocks

**Comment by zw963** [comment]
> 你的脚本能不能提供一个不用dnscrypt的？就是简单路由，国内走国内，国外走shadowsocks

有啊, chinadns 那个应该还工作, 虽然我自己好久没试了, 但是 DNS 污染是一个很严重的事情,
没有 dnscrypt, 用起来很不稳定的, 动不动打不开.

> [5538] 03 Dec 21:33:10.306 [err] [main.c:801] No (currently) valid certs found.

这个我大概知道什么原因了, 按照下面的顺序排查:

1. 你是不是[这样](https://github.com/cofyc/dnscrypt-wrapper/issues/153#issuecomment-394775651)生成证书的?  否则证书会过期.

2.  我加了 crontab, 每隔十分钟重启一次 server, 我不记得这个有没有用, 但是记得好像有证书 invalid 的问题, 才加的.

```
*/10 * * * * systemctl restart dnscrypt-wrapper
```

**Comment by momobile** [comment]
不是，我生成证书没有使用时效参数

我看你发给我的文章，那个人回复，即便你指定了365d，依然还要每天重启一次进程啊？

**Comment by zw963** [comment]
> 我看你发给我的文章，那个人回复，即便你指定了365d，依然还要每天重启一次进程啊？

你看错了, 不用, 这是 dnscrypt-server 配置过期的问题, 不属于这个脚本的问题.
