### ISSUE TITLE
所有流量都走了全局

### ISSUE THREAD

**Issue by WhatAKitty** [zw963/asuswrt-merlin-transparent-proxy#66]
首先，非常感谢这个仓库让我的路由器能够自动代理。

但是，在使用过程中，发现了一个问题，能否请教一下。非常感谢~

具体问题描述：
这边发现开启代理后，所有流量都走了全局。包括打开百度也是。然后默认通过ip.cn这个网站，可以看到我的ip是代理服务器的ip。

额外的信息：
路由器：AC66U
梅林版本：380.70
使用的代理方案：ss+dnsmasq+dnscrypt 

需要求教的问题：
是否能够做到PAC的效果？

**Comment by zw963** [comment]
有两个愿意可能导致这个问题:

1.   `ipset -L CHINAIPS |wc -l`, 这个结果应该是 8000 多条.
2.  `cat /opt/etc/dnsmasq.d/accelerated-domains.china.conf |wc -l`, 这个应该是 50000 多条.

如果不是, 那就是部署有问题, 重新部署下.

如果不行, 贴下列命令执行输出日志:

```sh
sh -x ./ss+dnsmasq+dnscrypt admin@router.asus.com
```

**Comment by gitx6** [comment]
本地电脑的代理服务软件关闭了么？
