### ISSUE TITLE
ip111.cn 国内测试为国内ip, 国外测试ip为vps的ip, 从谷歌测试无ip

### ISSUE THREAD

**Issue by a1e1c1f5** [zw963/asuswrt-merlin-transparent-proxy#68]
1.
使用ss+dnsmasq+dnscrypt方式, 启动后无法科学上网
dnscrypt-wrapper自己搭建的, 未发现问题.
ip111.cn的测试结果:
     国内测试为国内ip, 国外测试ip为vps的ip, 从谷歌测试无ip
2.
使用ss+chinadns+dnscrypt 能够使用google, 但是youtobe不能建立https连接(不是私密链接), twitter不能使用. 

3. ss+dnsmasq+udprelay 和 ss+chinadns 不能科学上网. 其中ss+dnsmasq+udprelay在ip111.cn的测试结果同样国内测试为国内ip, 国外测试ip为vps的ip, 从谷歌测试无ip

路由器 66U-B1, 北京联通光纤

**Comment by zw963** [comment]
这个, 你提供的信息有点少, 很难排查, 目测可能是 DNS 被劫持的问题, 即: dnscrypt 没有生效,
你有试过开启 [tcp_only]( https://github.com/zw963/asuswrt-merlin-transparent-proxy/wiki#%E8%BF%9E%E6%8E%A5%E5%88%B0%E8%BF%9C%E7%A8%8B-dnscrypt-%E6%9C%8D%E5%8A%A1%E5%99%A8-%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6) 吗?

**Comment by gitx6** [comment]
+dnscrypt方式可以参照issue #67 改为dnscrypt-proxy2，无需自己搭建dnscrypt-wrapper
+udprelay方式影响出国因素太多，很可能出不去
单独的chinadns因为dns污染，肯定出不去

**Comment by a1e1c1f5** [comment]
> 这个, 你提供的信息有点少, 很难排查, 目测可能是 DNS 被劫持的问题, 即: dnscrypt 没有生效,
> 你有试过开启 [tcp_only]吗?
试过tcp_only, 好像没起作用. 我再具体看一下吧,谢谢啦.!




> +dnscrypt方式可以参照issue #67 改为dnscrypt-proxy2，无需自己搭建dnscrypt-wrapper
> +udprelay方式影响出国因素太多，很可能出不去
> 单独的chinadns因为dns污染，肯定出不去
我试试dnscrypt-proxy2, 谢谢啦!
