### ISSUE TITLE
MacOS: sed: illegal option - r

### ISSUE THREAD

**Issue by chenshifei** [zw963/asuswrt-merlin-transparent-proxy#7]
The `sed` shipped with MacOS is a little bit different with the standard gnu-sed, which couldn't recognize `-r` option.

So running `./generate_dns` would result in an empty `accelerated-domains-ipset.china.conf`, and all of the request would be carried out by shadowsocks.
#
Added some explanations to the README.md in PR #6

**Comment by zw963** [comment]
应该已经修正 1c7cc9b
