### ISSUE TITLE
ss+dnsmasq+dnscrypt部署失败

### ISSUE THREAD

**Issue by ghost** [zw963/asuswrt-merlin-transparent-proxy#70]
你好：我按照wiki部署ss+dnsmasq+dnscrypt方式没成功，因为不太懂这玩意，按照wiki搞了好几天了。还请指导下。
下面是我的操作步骤：
设备华硕AC66U 380.70固件，VirtualBox安装ubuntu-18.04.1
1、首先打开路由器的JFFS和SSH。
2、插上U盘通过虚拟机Ubuntu SSH到路由器将U盘格式化成ext3格式
3、安装entware-setup.s，安装完成后运行opkg --version,返回版本：opkg version 0.1.8
4、在Ubuntu里下载项目，Terminal里运行代码：curl -L https://github.com/zw963/asuswrt-merlin-transparent-proxy/archive/master.zip > transparent-proxy.zip
5、解压，Terminal里运行代码：unzip transparent-proxy.zip
6、进入项目目录，Terminal里运行：cd ~/asuswrt-merlin-transparent-proxy-master
7、创建JSON脚本，Terminal里运行：touch router/opt/etc/shadowsocks.json，然后使用编辑器添加内容。
8、运行一键部署脚本，Terminal里运行./ss+dnsmasq+dnscrypt admin@192.168.50.1，然后返回下面两条信息：
sh: /opt/etc/toggle_proxy.sh: not found
local file router/opt/etc/dnscrypt-proxy.sh is missing ...
呃……不知道怎么搞了求指导。

**Comment by gitx6** [comment]
你vps上面部署dnscrpty-wrapper了么？

**Comment by dreamhb** [comment]
dnscrypt-proxy.sh 这个文件没有，我运行脚本也是这个错误

**Comment by zw963** [comment]
路由器的 `/opt/etc/dnscrypt-proxy.sh` 这个文件要你自己创建, 或者在部署前, 部署目录下面,增加 `router/opt/etc/dnscrypt-proxy.sh`, 内容参考 WIKI.

**Comment by erlijie** [comment]
win10下，同样失败了。
