### ISSUE TITLE
添加域名白名单 (国内的域名) 无效

### ISSUE THREAD

**Issue by momobile** [zw963/asuswrt-merlin-transparent-proxy#71]
user_domain_name_whitelist.txt 中添加域名，执行生效的脚本，然后不生效，重启一遍路由器依然不生效。不知道还不在？能不能帮忙看看为啥？

**Comment by zw963** [comment]
验证下你自己新增的域名，在运行 /opt/etc/patch_router 之后，有没有被增加到 `/opt/etc/dnsmasq.d/whitelist-domains.china.conf` 文件中，例如：

```sh
# cat /opt/etc/user_domain_name_whitelist.txt
test123.com
# cat /opt/etc/dnsmasq.d/whitelist-domains.china.conf
server=/test123.com/114.114.114.114
```

**Comment by momobile** [comment]
在的！起初发现无效，我通过ip白名单配置了。现在我把ip白名单去掉，留下了域名白名单。至少目前是奇效了。暂时先这样吧。有问题再提出来，谢谢！
