### ISSUE TITLE
[Bug] iptable restore 导致用户添加规则被覆盖

### ISSUE THREAD

**Issue by zeroohub** [zw963/asuswrt-merlin-transparent-proxy#72]
关于iptables有一个改进和一个bug:
**改进:** iptable 被系统刷新是发生在dhcp重新分配新外网地址的时候, 这个可以把原来使用cron的, 改为监听dhcpc-event.
**bug:** 与config_iptables脚本相关, 假设场景:
1. 跑config_iptables备份数据, 并配置规则
2. 用户在webui上添加了类似port forwarding这样的规则
3. ip whiltelist更新, iptable从备份还原, 再添加ss规则
4. webui配置丢失.

解决: 还原iptable不通过备份还原的方式, 而是使用类似
`iptables -t nat -D OUTPUT -p tcp -j SHADOWSOCKS_TCP` 
匹配删除规则的方式来还原.

**Comment by zw963** [comment]
谢谢你的建议，第二个 bug 我已经在 https://github.com/zw963/asuswrt-merlin-transparent-proxy/pull/73
中做了尝试性的修改，可能还有 BUG, 如果有空， 请帮忙测试一下。

**Comment by zw963** [comment]
至于第一个改进， 请提供一个 `监听dhcpc-event` 的示例, 我并没有明白这个应该如何做。

**Comment by zeroohub** [comment]
> 至于第一个改进， 请提供一个 `监听dhcpc-event` 的示例, 我并没有明白这个应该如何做。

在`/jffs/scripts/dhcpc-event` 脚本里加对应代码就好了, 跟你现有的`wan-start`一样.

**Comment by zw963** [comment]
以上问题已经修改.
