### ISSUE TITLE
rt-ac86u

### ISSUE THREAD

**Issue by le0lu0** [zw963/asuswrt-merlin-transparent-proxy#78]
asus rt-ac86u执行ss+dnsmasq+dnscrypt2时，无法成功，截图如下
![TIM截图20190407113442](https://user-images.githubusercontent.com/8571049/55678265-4654bb00-5929-11e9-883d-2335f8450c2f.png)

**Comment by le0lu0** [comment]
上面是在windows下gitbash下遇到的问题，使用Ubuntu已经没有这个问题了。
不过有新的问题：


![TIM截图20190407172524](https://user-images.githubusercontent.com/8571049/55681557-31dce680-595a-11e9-8d6d-69dd21a39c90.png)


路由器上已经执行过entware-setup.sh并且成功， opkg update && opkg upgrade都没问题。

**Comment by Acris** [comment]
路由器有装Entware吗？直接SSH登录路由器执行`opkg --version`试试？

**Comment by zw963** [comment]
没有反馈， 暂时关闭。
