### ISSUE TITLE
我不想使用dns加密，原来的脚本都没有了吗？

### ISSUE THREAD

**Issue by momobile** [zw963/asuswrt-merlin-transparent-proxy#80]
您好，现在部署脚本只剩下2个了吗？原来chinadns的不存在了吗？dns我这快不想使用加密的，就直接用google的就行。不知道现在还有没有这个选项！谢谢

**Comment by zw963** [comment]
https://github.com/zw963/asuswrt-merlin-transparent-proxy/releases/tag/v0.3.7

原来的没有 dnscrypt 加密的版本至少在上海是完全用不了的， 因为 DNS 投毒。
