### ISSUE TITLE
华硕ac66ub1 u盘安装 entware和ss 断电不丢配置 能否 咋做 求教

### ISSUE THREAD

**Issue by miaoweicn** [zw963/asuswrt-merlin-transparent-proxy#84]
git了大神一键脚本，经过几番折腾终于安装好了ss，上网速度也都很好。
现在特别想知道：断电重启怎么能不丢失配置？
不想重新来一遍 entware-setup.sh 和安装脚本这些配置。。。。。。哭死

**Comment by zw963** [comment]
断电重启本来就不会丢配置。你插 U 盘了吗？

**Comment by miaoweicn** [comment]
：）很感谢您的回复！已经解决了。
第一次因为我没有正确挂载/opt，导致断电重启丢了配置。
