### ISSUE TITLE
Any example of shadowsocks.config with v2ray enabled?

### ISSUE THREAD

**Issue by kfstorm** [zw963/asuswrt-merlin-transparent-proxy#86]
How do I fill `userid` and `alterid` in `shadowsocks.json` if I want to use v2ray?

**Comment by gitx6** [comment]
不能。这是SS的客户端，不是v2ray客户端。

**Comment by kfstorm** [comment]
> 不能。这是 SS 的客户端，不是 v2ray 客户端。

I noticed a `ss+dnsmasq+dnscrypt2+v2ray` file was added recently. It uses `v2ray-plugin`. But I can't find any instruction about how to modify the `shadowsocks.json` file to enable v2ray. I've searched https://github.com/shadowsocks/v2ray-plugin and found that `plugin_opts` may be the right place to fill v2ray parameters. But there's no documentation about `userid` and `alterid` fields which is required by my VPS provider.

**Comment by zw963** [comment]
https://github.com/shadowsocks/v2ray-plugin#usage

1. we add v2ray plugin options use command line argument `--plugin-opts "server"`, not shadowsocks.json.
2.  those options is seem like optional and only need set in server, for client,  only need `--plugin /opt/etc/v2ray-plugin_linux_arm5`.

you can always add supported options to shadowsocks.json if you want.

**Comment by kfstorm** [comment]
https://github.com/zw963/asuswrt-merlin-transparent-proxy/pull/77 only enables ss client and ss server to communicate via v2ray protocol. But it's not gonna work with ss client and v2ray server. Am I right?

**Comment by zw963** [comment]
> #77 only enables ss client and ss server to communicate via v2ray protocol. But it's not gonna work with ss client and v2ray server. Am I right?

Yes.
