### ISSUE TITLE
华硕AC86U是否可以刷呢？

### ISSUE THREAD

**Issue by KinseyWang** [zw963/asuswrt-merlin-transparent-proxy#87]
你好 请问以下我刚买的华硕AC86U可以刷吗？确切的说是在原本固件基础上装插件的形式么？
其实我并不懂程序 但我自己也可以按照教程架设了v2ray服务器 通过手机电脑上的SS客户端实现科学上网 也不算完全的伸手党
所以我很想知道怎样可以在我这台路由上实现科学上网……以及原理是什么

**Comment by zw963** [comment]
你需要先刷梅林, 請讀 WiKi.
