### ISSUE TITLE
ac86U执行一键部署后卡在shadowsocks.json上

### ISSUE THREAD

**Issue by haies** [zw963/asuswrt-merlin-transparent-proxy#88]
在wsl的ubuntu18.04中
按照步骤执行`./ss+dnsmasq+dnscrypt2 admin@192.168.50.1`后一直是以下界面
![image](https://user-images.githubusercontent.com/4749901/59427546-79299c80-8e0d-11e9-824d-bf134aa53ed0.png)

**Comment by zw963** [comment]
可能你的網絡是長城寬帶, 連接外網的出口太慢了, 我們需要連接到 entware 網站安裝所需的 package.

**Comment by haies** [comment]
我的是100m电信，在路由器上opkg install都正常。
此外我看脚步69行opkg install dnscrypt-proxy2_nohf
我手动在路由器上执行提示没有dnscrypt-proxy2_nohf，但是可以安装dnscrypt-proxy2，是不是opkg的源要设置一下？

**Comment by zw963** [comment]
可能是 ARM 不同版本兼容的问题? 如果将 dnscrypt-proxy2_nohf 改为 dnscrypt-proxy2 是否就可以用了?
