### ISSUE TITLE
部署完成以后， 路由器重启以后ss-redir好像无法自启动。需要手动启动？

### ISSUE THREAD

**Issue by wuly12345** [zw963/asuswrt-merlin-transparent-proxy#9]
看完了脚本， 似乎没有加自启动的脚本。 是么？？？

**Comment by zw963** [comment]
好吧, 被你发现了, 其实 ss-redir 启动了,  因为 ss-local 没有启动的必要, 我直接更改了 S22shadowsocks
中的 ss-local 为 ss-redir.

你最终启动不正常吗?

**Comment by zw963** [comment]
你尝试运行 `ps |grep ss-redir` 看下, 是否有类似 

```sh
  600 admin     5744 S    ss-redir -c /opt/etc/shadowsocks.json
```

如果没有, 那表示安装那里出错了.
