### ISSUE TITLE
请教一个问题，国内域名解析很慢，访问也很慢

### ISSUE THREAD

**Issue by momobile** [zw963/asuswrt-merlin-transparent-proxy#90]
你好，使用脚本部署，chinadns解析用户名，访问baidu（还有别的，但是百度最明显）特别慢，有时候还会现实服务器断开

虽然脚本是实现翻墙的，但是百度有些时候需要，离不开的。

请问如何调查？为啥

**Comment by zw963** [comment]
是不是你访问百度也翻墙了？ 请尝试访问 https://ip111.cn 查看访问国内网站的 ip 是多少。

**Comment by momobile** [comment]
我大概找到原因了，应该是ChinaDNS的上游服务器设置的原因。我调整了一下把114的排在了前面；114.114.114.114,208.67.222.222:443，现在秒开百度，但是貌似访问外国的开始慢了。。。哈哈

另外，我这里感觉dns污染并不严重，北京的联通。我把ss tunnel也disabled了。
