### ISSUE TITLE
v2ray support

### ISSUE THREAD

**Issue by kfstorm** [zw963/asuswrt-merlin-transparent-proxy#91]
If someone is interested in replacing shadowsocks with v2ray, here is an example: https://github.com/kfstorm/asuswrt-merlin-transparent-proxy.

**Comment by zw963** [comment]
Cool，非常感兴趣， 有空一定研究下，谢谢！

**Comment by zw963** [comment]
I update to use v2ray too, thank you!

**Comment by zw963** [comment]
Hi, @kfstorm , 我读到了 [这个](https://medium.com/@TachyonDevel/%E6%BC%AB%E8%B0%88%E5%90%84%E7%A7%8D%E9%BB%91%E7%A7%91%E6%8A%80%E5%BC%8F-dns-%E6%8A%80%E6%9C%AF%E5%9C%A8%E4%BB%A3%E7%90%86%E7%8E%AF%E5%A2%83%E4%B8%AD%E7%9A%84%E5%BA%94%E7%94%A8-62c50e58cbd0)  博客，一片很好的文章，其中讲到了 v2ray 中内置的 DNS 路由功能， 我还为尝试，不知你是否有做过测试， 用该功能取代 dnscrypt ?

**Comment by kfstorm** [comment]
这个我没有试过。当时想的是v2ray只是用来替换ss，所以我没有配置DNS，只是在inbound里加了sniffing，在路由规则里定义了`geosite:cn`和`geoip:cn`走直连。保留了路由表里的CHINAIPS和CHINAIP。我理解的是CHINAIPS可以转换为v2ray里的一个自定义geoip文件，不过似乎没有必要在v2ray里设置dns的配置（我的dnscrypt服务器和v2ray服务器是同一台）。

不过v2ray只能嗅探http和tls流量，如果从电脑端发出来的流量是其他tcp流量或者udp流量，那么路由器上的v2ray是没办法自行查询dns的，因为不知道域名。如果有国外网站的dns被污染成一个国内ip了，流量又不是HTTP(S)，那么v2ray也只好按直连处理了，即使没有配置国内ip走直连的规则，远端v2ray也只能把流量发送给被污染的IP。所以我觉得dnscrypt还是有存在的必要的，他排除了非HTTP请求被污染的风险。除非终端的DNS请求能直接被v2ray代理而不走运营商的DNS服务器？

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by zw963** [comment]
明白了， 谢谢， 看样子我的 v2ray 脚本还有改进的空间 (我的理解是可以使用 geoip:cn 来取代我目前那一大堆 iptables, 只需要保留 dnscrypt, 这才应该是目前使用 v2ray 的最佳方案吧。

**Comment by kfstorm** [comment]
是的，应该是可以用geoip:cn来替换iptables里的东西的。

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by gitx6** [comment]
换clash做客户端
https://github.com/KOP-XIAO/Clash-Merlin/wiki

**Comment by zw963** [comment]
@wangxin6 , @kfstorm , 你们在安卓手机上用什么 v2ray 客户端？ 

我目前不得不保留老的 ss-server, 并且在手机上使用小火箭连接，因为它很稳定.
如果使用 shadowsocks 协议连接 v2ray server, 非常不稳定，而且最近莫名其妙不可用了。

**Comment by gitx6** [comment]
Calsh A: https://github.com/ccg2018/ClashA/tree/master

**Comment by yzm157** [comment]
@kfstorm 在这里借个楼，我看了你的enable_swap.sh，dd命令创建的命令有点问题呀，bs=1k count=1048576, 创建1T的虚拟内存

**Comment by docete** [comment]
性能咋样？AC68U带着吃力吗？

**Comment by zw963** [comment]
@kfstorm , v2ray 4.22.0 发布了， 也许你感兴趣。https://t.me/s/v2fly.

这个版本带来了
1. DNS over HTTPS
百科 https://zh.wikipedia.org/wiki/DNS_over_HTTPS

2. ExpectIPs in DNS 会对返回的 IP 的进行校验，只返回包含 expectIPs 列表中的地址

这两个具体介绍和使用方法在 https://v2ray.com/chapter_02/04_dns.html

**Comment by zw963** [comment]
@kfstorm , maybe you want try this. (don't need ipset/dnsmasq/dnscrypt, V2ray only solution)
i use it several weeks, work well for me.

https://github.com/zw963/asuswrt-merlin-v2ray
