### ISSUE TITLE
如何支持SSR？

### ISSUE THREAD

**Issue by Journalist-HK** [zw963/asuswrt-merlin-transparent-proxy#92]
把 shadowsocks-libev 改成 shadowsocksr-libev 就可以了吗？

**Comment by zw963** [comment]
抱歉， 其实我并不知道这个 sr 和没有 sr 存在什么不同。

但是我搜索了下，发现 https://github.com/shadowsocksr-backup/shadowsocksr-libev
似乎多年不更新了， 因此，应该没有使用它的必要了。
