### ISSUE TITLE
`ssh admin@router.asus.com /opt/etc/toggle_proxy.sh disable` 问题

### ISSUE THREAD

**Issue by chinaq** [zw963/asuswrt-merlin-transparent-proxy#93]
`ssh admin@router.asus.com /opt/etc/toggle_proxy.sh disable` 使用后，一开使关闭了。过一段时间又会自动启动。一开始以为重启后会自动开启。但后来没有重启，也自动开启了。如果要完全关闭，需要时再手动开启，还有其他脚本吗？

另，`toggle_proxy.sh`中并没有发现关闭 ss 的命令，这有影响吗？还是我没发现？

**Comment by zw963** [comment]
> ssh admin@router.asus.com /opt/etc/toggle_proxy.sh disable 使用后，一开使关闭了。过一段时间又会自动启动。一开始以为重启后会自动开启。但后来没有重启，也自动开启了。如果要完全关闭，需要时再手动开启，还有其他脚本吗？

当 DHCP 重新分配 ip 地址的时候， 会再次执行 /opt/etc/apply_iptables_rule.sh, 但是诡异的是，当 disable 的时候，我有取消这个文件的可执行权限， 为啥会重新开启？ 你用的那个脚本部署的？

> 另，toggle_proxy.sh中并没有发现关闭 ss 的命令，这有影响吗？还是我没发现？

是啊， 我只是取消了 iptables, 没关 ss, 流量不走 ss 了而已。

**Comment by chinaq** [comment]
布署用的是 `ss+dnsmasq+dnscrypt2`，现在我的临时解决方案是，将 ss 的地址改成一个无效的地址，在需要的时候再改回来

**Comment by zw963** [comment]
最简单的办法， 上路由器, 运行:  `chmod -x /opt/etc/patch_router.sh`, 绝对不会再运行了。
