### ISSUE TITLE
user_domain_name_gfwlist的设置无法生效

### ISSUE THREAD

**Issue by Tlaster** [zw963/asuswrt-merlin-transparent-proxy#94]
比如把`ip111.cn`加进去之后执行了`patch_router`之后仍然显示是国内IP

**Comment by zw963** [comment]
被你发现了，这个只是将域名解析改为国外 DNS 而已，IP 显示是有问题，只是我自己目前没有在用了。

**Comment by zw963** [comment]
建议使用 v2ray 版本解决这个问题。https://github.com/zw963/asuswrt-merlin-v2ray
