### ISSUE TITLE
如何指定局域网某个固定IP不走代理？

### ISSUE THREAD

**Issue by macktheknife** [zw963/asuswrt-merlin-transparent-proxy#99]
主要目标是防止PT走相关代理，THKS

**Comment by zw963** [comment]
https://github.com/zw963/asuswrt-merlin-transparent-proxy/wiki#%E6%B7%BB%E5%8A%A0-ip-%E7%99%BD%E5%90%8D%E5%8D%95-%E5%B8%8C%E6%9C%9B%E7%BB%95%E8%BF%87%E4%BB%A3%E7%90%86%E7%9B%B4%E8%BF%9E%E7%9A%84-ip
